os.(*File).close STEXT dupok nosplit size=28 args=0x18 locals=0x0
	0x0000 00000 (<autogenerated>:1)	TEXT	os.(*File).close(SB), DUPOK|NOSPLIT|ABIInternal, $0-24
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$0, gclocals·e6397a44f8e1b6e77d0f200b4fba5269(SB)
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$1, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x0000 00000 (<autogenerated>:1)	XORPS	X0, X0
	0x0003 00003 (<autogenerated>:1)	MOVUPS	X0, "".~r0+16(SP)
	0x0008 00008 (<autogenerated>:1)	MOVQ	""..this+8(SP), AX
	0x000d 00013 (<autogenerated>:1)	TESTB	AL, (AX)
	0x000f 00015 (<autogenerated>:1)	MOVQ	(AX), AX
	0x0012 00018 (<autogenerated>:1)	MOVQ	AX, ""..this+8(SP)
	0x0017 00023 (<autogenerated>:1)	JMP	os.(*file).close(SB)
	0x0000 0f 57 c0 0f 11 44 24 10 48 8b 44 24 08 84 00 48  .W...D$.H.D$...H
	0x0010 8b 00 48 89 44 24 08 e9 00 00 00 00              ..H.D$......
	rel 24+4 t=8 os.(*file).close+0
"".main STEXT size=1086 args=0x0 locals=0x1c8
	0x0000 00000 (main.go:7)	TEXT	"".main(SB), ABIInternal, $456-0
	0x0000 00000 (main.go:7)	MOVQ	(TLS), CX
	0x0009 00009 (main.go:7)	LEAQ	-328(SP), AX
	0x0011 00017 (main.go:7)	CMPQ	AX, 16(CX)
	0x0015 00021 (main.go:7)	PCDATA	$0, $-2
	0x0015 00021 (main.go:7)	JLS	1076
	0x001b 00027 (main.go:7)	PCDATA	$0, $-1
	0x001b 00027 (main.go:7)	SUBQ	$456, SP
	0x0022 00034 (main.go:7)	MOVQ	BP, 448(SP)
	0x002a 00042 (main.go:7)	LEAQ	448(SP), BP
	0x0032 00050 (main.go:7)	FUNCDATA	$0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0032 00050 (main.go:7)	FUNCDATA	$1, gclocals·12e398377374b01c940a47142b280e95(SB)
	0x0032 00050 (main.go:7)	FUNCDATA	$3, "".main.stkobj(SB)
	0x0032 00050 (main.go:8)	MOVQ	$200, "".x+64(SP)
	0x003b 00059 (main.go:11)	MOVQ	$200, (SP)
	0x0043 00067 (main.go:11)	PCDATA	$1, $0
	0x0043 00067 (main.go:11)	CALL	runtime.convT64(SB)
	0x0048 00072 (main.go:11)	MOVQ	8(SP), AX
	0x004d 00077 (main.go:11)	MOVQ	AX, ""..autotmp_19+136(SP)
	0x0055 00085 (main.go:11)	LEAQ	type.int(SB), CX
	0x005c 00092 (main.go:11)	MOVQ	CX, "".any+224(SP)
	0x0064 00100 (main.go:11)	MOVQ	AX, "".any+232(SP)
	0x006c 00108 (main.go:12)	MOVQ	CX, "".~arg0+160(SP)
	0x0074 00116 (main.go:12)	MOVQ	AX, "".~arg0+168(SP)
	0x007c 00124 (main.go:12)	XORPS	X0, X0
	0x007f 00127 (main.go:12)	MOVUPS	X0, ""..autotmp_22+320(SP)
	0x0087 00135 (main.go:12)	LEAQ	""..autotmp_22+320(SP), AX
	0x008f 00143 (main.go:12)	MOVQ	AX, ""..autotmp_20+128(SP)
	0x0097 00151 (main.go:12)	TESTB	AL, (AX)
	0x0099 00153 (main.go:12)	MOVQ	"".~arg0+160(SP), CX
	0x00a1 00161 (main.go:12)	MOVQ	"".~arg0+168(SP), DX
	0x00a9 00169 (main.go:12)	MOVQ	CX, ""..autotmp_22+320(SP)
	0x00b1 00177 (main.go:12)	MOVQ	DX, ""..autotmp_22+328(SP)
	0x00b9 00185 (main.go:12)	TESTB	AL, (AX)
	0x00bb 00187 (main.go:12)	JMP	189
	0x00bd 00189 (main.go:12)	MOVQ	AX, fmt.a+376(SP)
	0x00c5 00197 (main.go:12)	MOVQ	$1, fmt.a+384(SP)
	0x00d1 00209 (main.go:12)	MOVQ	$1, fmt.a+392(SP)
	0x00dd 00221 (main.go:12)	MOVQ	$0, fmt.n+72(SP)
	0x00e6 00230 (main.go:12)	XORPS	X0, X0
	0x00e9 00233 (main.go:12)	MOVUPS	X0, fmt.err+192(SP)
	0x00f1 00241 (<unknown line number>)	NOP
	0x00f1 00241 (main.go:12)	MOVQ	$0, fmt..autotmp_3+88(SP)
	0x00fa 00250 (main.go:12)	XORPS	X0, X0
	0x00fd 00253 (main.go:12)	MOVUPS	X0, fmt..autotmp_4+240(SP)
	0x0105 00261 ($GOROOT/src/fmt/print.go:274)	XORPS	X0, X0
	0x0108 00264 ($GOROOT/src/fmt/print.go:274)	MOVUPS	X0, ""..autotmp_17+336(SP)
	0x0110 00272 ($GOROOT/src/fmt/print.go:274)	MOVQ	os.Stdout(SB), AX
	0x0117 00279 ($GOROOT/src/fmt/print.go:274)	LEAQ	go.itab.*os.File,io.Writer(SB), CX
	0x011e 00286 ($GOROOT/src/fmt/print.go:274)	MOVQ	CX, (SP)
	0x0122 00290 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, 8(SP)
	0x0127 00295 ($GOROOT/src/fmt/print.go:274)	MOVQ	fmt.a+376(SP), AX
	0x012f 00303 ($GOROOT/src/fmt/print.go:274)	MOVQ	fmt.a+384(SP), CX
	0x0137 00311 ($GOROOT/src/fmt/print.go:274)	MOVQ	fmt.a+392(SP), DX
	0x013f 00319 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, 16(SP)
	0x0144 00324 ($GOROOT/src/fmt/print.go:274)	MOVQ	CX, 24(SP)
	0x0149 00329 ($GOROOT/src/fmt/print.go:274)	MOVQ	DX, 32(SP)
	0x014e 00334 ($GOROOT/src/fmt/print.go:274)	CALL	fmt.Fprintln(SB)
	0x0153 00339 ($GOROOT/src/fmt/print.go:274)	MOVQ	40(SP), AX
	0x0158 00344 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, ""..autotmp_16+104(SP)
	0x015d 00349 ($GOROOT/src/fmt/print.go:274)	MOVQ	48(SP), AX
	0x0162 00354 ($GOROOT/src/fmt/print.go:274)	MOVQ	56(SP), CX
	0x0167 00359 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, ""..autotmp_17+336(SP)
	0x016f 00367 ($GOROOT/src/fmt/print.go:274)	MOVQ	CX, ""..autotmp_17+344(SP)
	0x0177 00375 ($GOROOT/src/fmt/print.go:274)	MOVQ	""..autotmp_16+104(SP), AX
	0x017c 00380 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, fmt..autotmp_3+88(SP)
	0x0181 00385 ($GOROOT/src/fmt/print.go:274)	MOVQ	""..autotmp_17+336(SP), AX
	0x0189 00393 ($GOROOT/src/fmt/print.go:274)	MOVQ	""..autotmp_17+344(SP), CX
	0x0191 00401 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, fmt..autotmp_4+240(SP)
	0x0199 00409 ($GOROOT/src/fmt/print.go:274)	MOVQ	CX, fmt..autotmp_4+248(SP)
	0x01a1 00417 (main.go:12)	MOVQ	fmt..autotmp_3+88(SP), AX
	0x01a6 00422 (main.go:12)	MOVQ	AX, fmt.n+72(SP)
	0x01ab 00427 (main.go:12)	MOVQ	fmt..autotmp_4+240(SP), AX
	0x01b3 00435 (main.go:12)	MOVQ	fmt..autotmp_4+248(SP), CX
	0x01bb 00443 (main.go:12)	MOVQ	AX, fmt.err+192(SP)
	0x01c3 00451 (main.go:12)	MOVQ	CX, fmt.err+200(SP)
	0x01cb 00459 (main.go:12)	JMP	461
	0x01cd 00461 (main.go:15)	MOVQ	$0, "".g+352(SP)
	0x01d9 00473 (main.go:15)	XORPS	X0, X0
	0x01dc 00476 (main.go:15)	MOVUPS	X0, "".g+360(SP)
	0x01e4 00484 (main.go:15)	LEAQ	go.string."Go"(SB), AX
	0x01eb 00491 (main.go:15)	MOVQ	AX, "".g+352(SP)
	0x01f3 00499 (main.go:15)	MOVQ	$2, "".g+360(SP)
	0x01ff 00511 (main.go:15)	MOVQ	$1, "".g+368(SP)
	0x020b 00523 (main.go:16)	MOVQ	AX, ""..autotmp_18+424(SP)
	0x0213 00531 (main.go:16)	MOVQ	$2, ""..autotmp_18+432(SP)
	0x021f 00543 (main.go:16)	MOVQ	$1, ""..autotmp_18+440(SP)
	0x022b 00555 (main.go:16)	LEAQ	go.itab."".Gopher,"".coder(SB), AX
	0x0232 00562 (main.go:16)	MOVQ	AX, (SP)
	0x0236 00566 (main.go:16)	LEAQ	""..autotmp_18+424(SP), AX
	0x023e 00574 (main.go:16)	MOVQ	AX, 8(SP)
	0x0243 00579 (main.go:16)	CALL	runtime.convT2I(SB)
	0x0248 00584 (main.go:16)	MOVQ	24(SP), AX
	0x024d 00589 (main.go:16)	MOVQ	16(SP), CX
	0x0252 00594 (main.go:16)	MOVQ	CX, "".c+208(SP)
	0x025a 00602 (main.go:16)	MOVQ	AX, "".c+216(SP)
	0x0262 00610 (main.go:17)	MOVQ	"".c+208(SP), AX
	0x026a 00618 (main.go:17)	MOVQ	"".c+216(SP), CX
	0x0272 00626 (main.go:17)	MOVQ	AX, ""..autotmp_24+288(SP)
	0x027a 00634 (main.go:17)	MOVQ	CX, ""..autotmp_24+296(SP)
	0x0282 00642 (main.go:17)	MOVQ	AX, ""..autotmp_25+120(SP)
	0x0287 00647 (main.go:17)	CMPQ	""..autotmp_25+120(SP), $0
	0x028d 00653 (main.go:17)	JNE	660
	0x028f 00655 (main.go:17)	JMP	1071
	0x0294 00660 (main.go:17)	MOVQ	8(AX), AX
	0x0298 00664 (main.go:17)	MOVQ	AX, ""..autotmp_25+120(SP)
	0x029d 00669 (main.go:17)	JMP	671
	0x029f 00671 (main.go:17)	MOVQ	""..autotmp_25+120(SP), AX
	0x02a4 00676 (main.go:17)	MOVQ	""..autotmp_24+296(SP), CX
	0x02ac 00684 (main.go:17)	MOVQ	AX, ""..autotmp_23+304(SP)
	0x02b4 00692 (main.go:17)	MOVQ	CX, ""..autotmp_23+312(SP)
	0x02bc 00700 (main.go:17)	MOVQ	AX, "".~arg0+144(SP)
	0x02c4 00708 (main.go:17)	MOVQ	CX, "".~arg0+152(SP)
	0x02cc 00716 (main.go:17)	XORPS	X0, X0
	0x02cf 00719 (main.go:17)	MOVUPS	X0, ""..autotmp_28+272(SP)
	0x02d7 00727 (main.go:17)	LEAQ	""..autotmp_28+272(SP), AX
	0x02df 00735 (main.go:17)	MOVQ	AX, ""..autotmp_26+112(SP)
	0x02e4 00740 (main.go:17)	TESTB	AL, (AX)
	0x02e6 00742 (main.go:17)	MOVQ	"".~arg0+144(SP), CX
	0x02ee 00750 (main.go:17)	MOVQ	"".~arg0+152(SP), DX
	0x02f6 00758 (main.go:17)	MOVQ	CX, ""..autotmp_28+272(SP)
	0x02fe 00766 (main.go:17)	MOVQ	DX, ""..autotmp_28+280(SP)
	0x0306 00774 (main.go:17)	TESTB	AL, (AX)
	0x0308 00776 (main.go:17)	JMP	778
	0x030a 00778 (main.go:17)	MOVQ	AX, fmt.a+400(SP)
	0x0312 00786 (main.go:17)	MOVQ	$1, fmt.a+408(SP)
	0x031e 00798 (main.go:17)	MOVQ	$1, fmt.a+416(SP)
	0x032a 00810 (main.go:17)	MOVQ	$0, fmt.n+80(SP)
	0x0333 00819 (main.go:17)	XORPS	X0, X0
	0x0336 00822 (main.go:17)	MOVUPS	X0, fmt.err+176(SP)
	0x033e 00830 (<unknown line number>)	NOP
	0x033e 00830 (main.go:12)	MOVQ	$0, fmt..autotmp_3+96(SP)
	0x0347 00839 (main.go:12)	XORPS	X0, X0
	0x034a 00842 (main.go:12)	MOVUPS	X0, fmt..autotmp_4+256(SP)
	0x0352 00850 ($GOROOT/src/fmt/print.go:274)	XORPS	X0, X0
	0x0355 00853 ($GOROOT/src/fmt/print.go:274)	MOVUPS	X0, ""..autotmp_17+336(SP)
	0x035d 00861 ($GOROOT/src/fmt/print.go:274)	MOVQ	os.Stdout(SB), AX
	0x0364 00868 ($GOROOT/src/fmt/print.go:274)	LEAQ	go.itab.*os.File,io.Writer(SB), CX
	0x036b 00875 ($GOROOT/src/fmt/print.go:274)	MOVQ	CX, (SP)
	0x036f 00879 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, 8(SP)
	0x0374 00884 ($GOROOT/src/fmt/print.go:274)	MOVQ	fmt.a+400(SP), AX
	0x037c 00892 ($GOROOT/src/fmt/print.go:274)	MOVQ	fmt.a+408(SP), CX
	0x0384 00900 ($GOROOT/src/fmt/print.go:274)	MOVQ	fmt.a+416(SP), DX
	0x038c 00908 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, 16(SP)
	0x0391 00913 ($GOROOT/src/fmt/print.go:274)	MOVQ	CX, 24(SP)
	0x0396 00918 ($GOROOT/src/fmt/print.go:274)	MOVQ	DX, 32(SP)
	0x039b 00923 ($GOROOT/src/fmt/print.go:274)	NOP
	0x03a0 00928 ($GOROOT/src/fmt/print.go:274)	CALL	fmt.Fprintln(SB)
	0x03a5 00933 ($GOROOT/src/fmt/print.go:274)	MOVQ	40(SP), AX
	0x03aa 00938 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, ""..autotmp_16+104(SP)
	0x03af 00943 ($GOROOT/src/fmt/print.go:274)	MOVQ	48(SP), AX
	0x03b4 00948 ($GOROOT/src/fmt/print.go:274)	MOVQ	56(SP), CX
	0x03b9 00953 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, ""..autotmp_17+336(SP)
	0x03c1 00961 ($GOROOT/src/fmt/print.go:274)	MOVQ	CX, ""..autotmp_17+344(SP)
	0x03c9 00969 ($GOROOT/src/fmt/print.go:274)	MOVQ	""..autotmp_16+104(SP), AX
	0x03ce 00974 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, fmt..autotmp_3+96(SP)
	0x03d3 00979 ($GOROOT/src/fmt/print.go:274)	MOVQ	""..autotmp_17+336(SP), AX
	0x03db 00987 ($GOROOT/src/fmt/print.go:274)	MOVQ	""..autotmp_17+344(SP), CX
	0x03e3 00995 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, fmt..autotmp_4+256(SP)
	0x03eb 01003 ($GOROOT/src/fmt/print.go:274)	MOVQ	CX, fmt..autotmp_4+264(SP)
	0x03f3 01011 (main.go:17)	MOVQ	fmt..autotmp_3+96(SP), AX
	0x03f8 01016 (main.go:17)	MOVQ	AX, fmt.n+80(SP)
	0x03fd 01021 (main.go:17)	MOVQ	fmt..autotmp_4+256(SP), AX
	0x0405 01029 (main.go:17)	MOVQ	fmt..autotmp_4+264(SP), CX
	0x040d 01037 (main.go:17)	MOVQ	AX, fmt.err+176(SP)
	0x0415 01045 (main.go:17)	MOVQ	CX, fmt.err+184(SP)
	0x041d 01053 (main.go:17)	JMP	1055
	0x041f 01055 (main.go:17)	PCDATA	$1, $-1
	0x041f 01055 (main.go:17)	MOVQ	448(SP), BP
	0x0427 01063 (main.go:17)	ADDQ	$456, SP
	0x042e 01070 (main.go:17)	RET
	0x042f 01071 (main.go:17)	JMP	671
	0x0434 01076 (main.go:17)	NOP
	0x0434 01076 (main.go:7)	PCDATA	$1, $-1
	0x0434 01076 (main.go:7)	PCDATA	$0, $-2
	0x0434 01076 (main.go:7)	CALL	runtime.morestack_noctxt(SB)
	0x0439 01081 (main.go:7)	PCDATA	$0, $-1
	0x0439 01081 (main.go:7)	JMP	0
	0x0000 65 48 8b 0c 25 00 00 00 00 48 8d 84 24 b8 fe ff  eH..%....H..$...
	0x0010 ff 48 3b 41 10 0f 86 19 04 00 00 48 81 ec c8 01  .H;A.......H....
	0x0020 00 00 48 89 ac 24 c0 01 00 00 48 8d ac 24 c0 01  ..H..$....H..$..
	0x0030 00 00 48 c7 44 24 40 c8 00 00 00 48 c7 04 24 c8  ..H.D$@....H..$.
	0x0040 00 00 00 e8 00 00 00 00 48 8b 44 24 08 48 89 84  ........H.D$.H..
	0x0050 24 88 00 00 00 48 8d 0d 00 00 00 00 48 89 8c 24  $....H......H..$
	0x0060 e0 00 00 00 48 89 84 24 e8 00 00 00 48 89 8c 24  ....H..$....H..$
	0x0070 a0 00 00 00 48 89 84 24 a8 00 00 00 0f 57 c0 0f  ....H..$.....W..
	0x0080 11 84 24 40 01 00 00 48 8d 84 24 40 01 00 00 48  ..$@...H..$@...H
	0x0090 89 84 24 80 00 00 00 84 00 48 8b 8c 24 a0 00 00  ..$......H..$...
	0x00a0 00 48 8b 94 24 a8 00 00 00 48 89 8c 24 40 01 00  .H..$....H..$@..
	0x00b0 00 48 89 94 24 48 01 00 00 84 00 eb 00 48 89 84  .H..$H.......H..
	0x00c0 24 78 01 00 00 48 c7 84 24 80 01 00 00 01 00 00  $x...H..$.......
	0x00d0 00 48 c7 84 24 88 01 00 00 01 00 00 00 48 c7 44  .H..$........H.D
	0x00e0 24 48 00 00 00 00 0f 57 c0 0f 11 84 24 c0 00 00  $H.....W....$...
	0x00f0 00 48 c7 44 24 58 00 00 00 00 0f 57 c0 0f 11 84  .H.D$X.....W....
	0x0100 24 f0 00 00 00 0f 57 c0 0f 11 84 24 50 01 00 00  $.....W....$P...
	0x0110 48 8b 05 00 00 00 00 48 8d 0d 00 00 00 00 48 89  H......H......H.
	0x0120 0c 24 48 89 44 24 08 48 8b 84 24 78 01 00 00 48  .$H.D$.H..$x...H
	0x0130 8b 8c 24 80 01 00 00 48 8b 94 24 88 01 00 00 48  ..$....H..$....H
	0x0140 89 44 24 10 48 89 4c 24 18 48 89 54 24 20 e8 00  .D$.H.L$.H.T$ ..
	0x0150 00 00 00 48 8b 44 24 28 48 89 44 24 68 48 8b 44  ...H.D$(H.D$hH.D
	0x0160 24 30 48 8b 4c 24 38 48 89 84 24 50 01 00 00 48  $0H.L$8H..$P...H
	0x0170 89 8c 24 58 01 00 00 48 8b 44 24 68 48 89 44 24  ..$X...H.D$hH.D$
	0x0180 58 48 8b 84 24 50 01 00 00 48 8b 8c 24 58 01 00  XH..$P...H..$X..
	0x0190 00 48 89 84 24 f0 00 00 00 48 89 8c 24 f8 00 00  .H..$....H..$...
	0x01a0 00 48 8b 44 24 58 48 89 44 24 48 48 8b 84 24 f0  .H.D$XH.D$HH..$.
	0x01b0 00 00 00 48 8b 8c 24 f8 00 00 00 48 89 84 24 c0  ...H..$....H..$.
	0x01c0 00 00 00 48 89 8c 24 c8 00 00 00 eb 00 48 c7 84  ...H..$......H..
	0x01d0 24 60 01 00 00 00 00 00 00 0f 57 c0 0f 11 84 24  $`........W....$
	0x01e0 68 01 00 00 48 8d 05 00 00 00 00 48 89 84 24 60  h...H......H..$`
	0x01f0 01 00 00 48 c7 84 24 68 01 00 00 02 00 00 00 48  ...H..$h.......H
	0x0200 c7 84 24 70 01 00 00 01 00 00 00 48 89 84 24 a8  ..$p.......H..$.
	0x0210 01 00 00 48 c7 84 24 b0 01 00 00 02 00 00 00 48  ...H..$........H
	0x0220 c7 84 24 b8 01 00 00 01 00 00 00 48 8d 05 00 00  ..$........H....
	0x0230 00 00 48 89 04 24 48 8d 84 24 a8 01 00 00 48 89  ..H..$H..$....H.
	0x0240 44 24 08 e8 00 00 00 00 48 8b 44 24 18 48 8b 4c  D$......H.D$.H.L
	0x0250 24 10 48 89 8c 24 d0 00 00 00 48 89 84 24 d8 00  $.H..$....H..$..
	0x0260 00 00 48 8b 84 24 d0 00 00 00 48 8b 8c 24 d8 00  ..H..$....H..$..
	0x0270 00 00 48 89 84 24 20 01 00 00 48 89 8c 24 28 01  ..H..$ ...H..$(.
	0x0280 00 00 48 89 44 24 78 48 83 7c 24 78 00 75 05 e9  ..H.D$xH.|$x.u..
	0x0290 9b 01 00 00 48 8b 40 08 48 89 44 24 78 eb 00 48  ....H.@.H.D$x..H
	0x02a0 8b 44 24 78 48 8b 8c 24 28 01 00 00 48 89 84 24  .D$xH..$(...H..$
	0x02b0 30 01 00 00 48 89 8c 24 38 01 00 00 48 89 84 24  0...H..$8...H..$
	0x02c0 90 00 00 00 48 89 8c 24 98 00 00 00 0f 57 c0 0f  ....H..$.....W..
	0x02d0 11 84 24 10 01 00 00 48 8d 84 24 10 01 00 00 48  ..$....H..$....H
	0x02e0 89 44 24 70 84 00 48 8b 8c 24 90 00 00 00 48 8b  .D$p..H..$....H.
	0x02f0 94 24 98 00 00 00 48 89 8c 24 10 01 00 00 48 89  .$....H..$....H.
	0x0300 94 24 18 01 00 00 84 00 eb 00 48 89 84 24 90 01  .$........H..$..
	0x0310 00 00 48 c7 84 24 98 01 00 00 01 00 00 00 48 c7  ..H..$........H.
	0x0320 84 24 a0 01 00 00 01 00 00 00 48 c7 44 24 50 00  .$........H.D$P.
	0x0330 00 00 00 0f 57 c0 0f 11 84 24 b0 00 00 00 48 c7  ....W....$....H.
	0x0340 44 24 60 00 00 00 00 0f 57 c0 0f 11 84 24 00 01  D$`.....W....$..
	0x0350 00 00 0f 57 c0 0f 11 84 24 50 01 00 00 48 8b 05  ...W....$P...H..
	0x0360 00 00 00 00 48 8d 0d 00 00 00 00 48 89 0c 24 48  ....H......H..$H
	0x0370 89 44 24 08 48 8b 84 24 90 01 00 00 48 8b 8c 24  .D$.H..$....H..$
	0x0380 98 01 00 00 48 8b 94 24 a0 01 00 00 48 89 44 24  ....H..$....H.D$
	0x0390 10 48 89 4c 24 18 48 89 54 24 20 0f 1f 44 00 00  .H.L$.H.T$ ..D..
	0x03a0 e8 00 00 00 00 48 8b 44 24 28 48 89 44 24 68 48  .....H.D$(H.D$hH
	0x03b0 8b 44 24 30 48 8b 4c 24 38 48 89 84 24 50 01 00  .D$0H.L$8H..$P..
	0x03c0 00 48 89 8c 24 58 01 00 00 48 8b 44 24 68 48 89  .H..$X...H.D$hH.
	0x03d0 44 24 60 48 8b 84 24 50 01 00 00 48 8b 8c 24 58  D$`H..$P...H..$X
	0x03e0 01 00 00 48 89 84 24 00 01 00 00 48 89 8c 24 08  ...H..$....H..$.
	0x03f0 01 00 00 48 8b 44 24 60 48 89 44 24 50 48 8b 84  ...H.D$`H.D$PH..
	0x0400 24 00 01 00 00 48 8b 8c 24 08 01 00 00 48 89 84  $....H..$....H..
	0x0410 24 b0 00 00 00 48 89 8c 24 b8 00 00 00 eb 00 48  $....H..$......H
	0x0420 8b ac 24 c0 01 00 00 48 81 c4 c8 01 00 00 c3 e9  ..$....H........
	0x0430 6b fe ff ff e8 00 00 00 00 e9 c2 fb ff ff        k.............
	rel 5+4 t=17 TLS+0
	rel 68+4 t=8 runtime.convT64+0
	rel 88+4 t=16 type.int+0
	rel 275+4 t=16 os.Stdout+0
	rel 282+4 t=16 go.itab.*os.File,io.Writer+0
	rel 335+4 t=8 fmt.Fprintln+0
	rel 487+4 t=16 go.string."Go"+0
	rel 558+4 t=16 go.itab."".Gopher,"".coder+0
	rel 580+4 t=8 runtime.convT2I+0
	rel 864+4 t=16 os.Stdout+0
	rel 871+4 t=16 go.itab.*os.File,io.Writer+0
	rel 929+4 t=8 fmt.Fprintln+0
	rel 1077+4 t=8 runtime.morestack_noctxt+0
type..eq."".Gopher STEXT dupok size=242 args=0x18 locals=0x58
	0x0000 00000 (<autogenerated>:1)	TEXT	type..eq."".Gopher(SB), DUPOK|ABIInternal, $88-24
	0x0000 00000 (<autogenerated>:1)	MOVQ	(TLS), CX
	0x0009 00009 (<autogenerated>:1)	CMPQ	SP, 16(CX)
	0x000d 00013 (<autogenerated>:1)	PCDATA	$0, $-2
	0x000d 00013 (<autogenerated>:1)	JLS	232
	0x0013 00019 (<autogenerated>:1)	PCDATA	$0, $-1
	0x0013 00019 (<autogenerated>:1)	SUBQ	$88, SP
	0x0017 00023 (<autogenerated>:1)	MOVQ	BP, 80(SP)
	0x001c 00028 (<autogenerated>:1)	LEAQ	80(SP), BP
	0x0021 00033 (<autogenerated>:1)	FUNCDATA	$0, gclocals·dc9b0298814590ca3ffc3a889546fc8b(SB)
	0x0021 00033 (<autogenerated>:1)	FUNCDATA	$1, gclocals·2589ca35330fc0fce83503f4569854a0(SB)
	0x0021 00033 (<autogenerated>:1)	MOVB	$0, "".r+112(SP)
	0x0026 00038 (<autogenerated>:1)	MOVQ	"".p+96(SP), AX
	0x002b 00043 (<autogenerated>:1)	MOVQ	8(AX), AX
	0x002f 00047 (<autogenerated>:1)	MOVQ	AX, ""..autotmp_5+56(SP)
	0x0034 00052 (<autogenerated>:1)	MOVQ	"".q+104(SP), AX
	0x0039 00057 (<autogenerated>:1)	MOVQ	8(AX), AX
	0x003d 00061 (<autogenerated>:1)	MOVQ	AX, ""..autotmp_6+48(SP)
	0x0042 00066 (<autogenerated>:1)	CMPQ	""..autotmp_5+56(SP), AX
	0x0047 00071 (<autogenerated>:1)	SETEQ	AL
	0x004a 00074 (<autogenerated>:1)	MOVB	AL, ""..autotmp_4+38(SP)
	0x004e 00078 (<autogenerated>:1)	JEQ	85
	0x0050 00080 (<autogenerated>:1)	JMP	230
	0x0055 00085 (<autogenerated>:1)	MOVQ	"".p+96(SP), AX
	0x005a 00090 (<autogenerated>:1)	MOVQ	8(AX), AX
	0x005e 00094 (<autogenerated>:1)	MOVQ	AX, ""..autotmp_7+40(SP)
	0x0063 00099 (<autogenerated>:1)	MOVQ	"".p+96(SP), AX
	0x0068 00104 (<autogenerated>:1)	MOVQ	(AX), AX
	0x006b 00107 (<autogenerated>:1)	MOVQ	AX, ""..autotmp_9+64(SP)
	0x0070 00112 (<autogenerated>:1)	MOVQ	"".q+104(SP), AX
	0x0075 00117 (<autogenerated>:1)	MOVQ	(AX), AX
	0x0078 00120 (<autogenerated>:1)	MOVQ	AX, ""..autotmp_10+72(SP)
	0x007d 00125 (<autogenerated>:1)	MOVQ	""..autotmp_9+64(SP), CX
	0x0082 00130 (<autogenerated>:1)	MOVQ	CX, (SP)
	0x0086 00134 (<autogenerated>:1)	MOVQ	AX, 8(SP)
	0x008b 00139 (<autogenerated>:1)	MOVQ	""..autotmp_7+40(SP), AX
	0x0090 00144 (<autogenerated>:1)	MOVQ	AX, 16(SP)
	0x0095 00149 (<autogenerated>:1)	PCDATA	$1, $0
	0x0095 00149 (<autogenerated>:1)	CALL	runtime.memequal(SB)
	0x009a 00154 (<autogenerated>:1)	MOVBLZX	24(SP), AX
	0x009f 00159 (<autogenerated>:1)	MOVB	AL, ""..autotmp_8+37(SP)
	0x00a3 00163 (<autogenerated>:1)	MOVB	AL, ""..autotmp_4+38(SP)
	0x00a7 00167 (<autogenerated>:1)	JMP	169
	0x00a9 00169 (<autogenerated>:1)	MOVBLZX	""..autotmp_4+38(SP), AX
	0x00ae 00174 (<autogenerated>:1)	MOVB	AL, ""..autotmp_3+39(SP)
	0x00b2 00178 (<autogenerated>:1)	TESTB	AL, AL
	0x00b4 00180 (<autogenerated>:1)	JNE	184
	0x00b6 00182 (<autogenerated>:1)	JMP	228
	0x00b8 00184 (<autogenerated>:1)	MOVQ	"".p+96(SP), AX
	0x00bd 00189 (<autogenerated>:1)	MOVQ	"".q+104(SP), CX
	0x00c2 00194 (<autogenerated>:1)	MOVQ	16(CX), CX
	0x00c6 00198 (<autogenerated>:1)	CMPQ	16(AX), CX
	0x00ca 00202 (<autogenerated>:1)	SETEQ	""..autotmp_3+39(SP)
	0x00cf 00207 (<autogenerated>:1)	JMP	209
	0x00d1 00209 (<autogenerated>:1)	MOVBLZX	""..autotmp_3+39(SP), AX
	0x00d6 00214 (<autogenerated>:1)	MOVB	AL, "".r+112(SP)
	0x00da 00218 (<autogenerated>:1)	MOVQ	80(SP), BP
	0x00df 00223 (<autogenerated>:1)	ADDQ	$88, SP
	0x00e3 00227 (<autogenerated>:1)	RET
	0x00e4 00228 (<autogenerated>:1)	PCDATA	$1, $-1
	0x00e4 00228 (<autogenerated>:1)	JMP	209
	0x00e6 00230 (<autogenerated>:1)	JMP	169
	0x00e8 00232 (<autogenerated>:1)	NOP
	0x00e8 00232 (<autogenerated>:1)	PCDATA	$1, $-1
	0x00e8 00232 (<autogenerated>:1)	PCDATA	$0, $-2
	0x00e8 00232 (<autogenerated>:1)	CALL	runtime.morestack_noctxt(SB)
	0x00ed 00237 (<autogenerated>:1)	PCDATA	$0, $-1
	0x00ed 00237 (<autogenerated>:1)	JMP	0
	0x0000 65 48 8b 0c 25 00 00 00 00 48 3b 61 10 0f 86 d5  eH..%....H;a....
	0x0010 00 00 00 48 83 ec 58 48 89 6c 24 50 48 8d 6c 24  ...H..XH.l$PH.l$
	0x0020 50 c6 44 24 70 00 48 8b 44 24 60 48 8b 40 08 48  P.D$p.H.D$`H.@.H
	0x0030 89 44 24 38 48 8b 44 24 68 48 8b 40 08 48 89 44  .D$8H.D$hH.@.H.D
	0x0040 24 30 48 39 44 24 38 0f 94 c0 88 44 24 26 74 05  $0H9D$8....D$&t.
	0x0050 e9 91 00 00 00 48 8b 44 24 60 48 8b 40 08 48 89  .....H.D$`H.@.H.
	0x0060 44 24 28 48 8b 44 24 60 48 8b 00 48 89 44 24 40  D$(H.D$`H..H.D$@
	0x0070 48 8b 44 24 68 48 8b 00 48 89 44 24 48 48 8b 4c  H.D$hH..H.D$HH.L
	0x0080 24 40 48 89 0c 24 48 89 44 24 08 48 8b 44 24 28  $@H..$H.D$.H.D$(
	0x0090 48 89 44 24 10 e8 00 00 00 00 0f b6 44 24 18 88  H.D$........D$..
	0x00a0 44 24 25 88 44 24 26 eb 00 0f b6 44 24 26 88 44  D$%.D$&....D$&.D
	0x00b0 24 27 84 c0 75 02 eb 2c 48 8b 44 24 60 48 8b 4c  $'..u..,H.D$`H.L
	0x00c0 24 68 48 8b 49 10 48 39 48 10 0f 94 44 24 27 eb  $hH.I.H9H...D$'.
	0x00d0 00 0f b6 44 24 27 88 44 24 70 48 8b 6c 24 50 48  ...D$'.D$pH.l$PH
	0x00e0 83 c4 58 c3 eb eb eb c1 e8 00 00 00 00 e9 0e ff  ..X.............
	0x00f0 ff ff                                            ..
	rel 5+4 t=17 TLS+0
	rel 150+4 t=8 runtime.memequal+0
	rel 233+4 t=8 runtime.morestack_noctxt+0
"".(*Gopher).code STEXT dupok size=645 args=0x8 locals=0x120
	0x0000 00000 (<autogenerated>:1)	TEXT	"".(*Gopher).code(SB), DUPOK|WRAPPER|ABIInternal, $288-8
	0x0000 00000 (<autogenerated>:1)	MOVQ	(TLS), CX
	0x0009 00009 (<autogenerated>:1)	LEAQ	-160(SP), AX
	0x0011 00017 (<autogenerated>:1)	CMPQ	AX, 16(CX)
	0x0015 00021 (<autogenerated>:1)	PCDATA	$0, $-2
	0x0015 00021 (<autogenerated>:1)	JLS	608
	0x001b 00027 (<autogenerated>:1)	PCDATA	$0, $-1
	0x001b 00027 (<autogenerated>:1)	SUBQ	$288, SP
	0x0022 00034 (<autogenerated>:1)	MOVQ	BP, 280(SP)
	0x002a 00042 (<autogenerated>:1)	LEAQ	280(SP), BP
	0x0032 00050 (<autogenerated>:1)	MOVQ	32(CX), BX
	0x0036 00054 (<autogenerated>:1)	TESTQ	BX, BX
	0x0039 00057 (<autogenerated>:1)	JNE	618
	0x003f 00063 (<autogenerated>:1)	NOP
	0x003f 00063 (<autogenerated>:1)	FUNCDATA	$0, gclocals·1a65e721a2ccc325b382662e7ffee780(SB)
	0x003f 00063 (<autogenerated>:1)	FUNCDATA	$1, gclocals·000713d0e9e44438ca2d32aa6561c14c(SB)
	0x003f 00063 (<autogenerated>:1)	FUNCDATA	$3, "".(*Gopher).code.stkobj(SB)
	0x003f 00063 (<autogenerated>:1)	CMPQ	""..this+296(SP), $0
	0x0048 00072 (<autogenerated>:1)	JNE	79
	0x004a 00074 (<autogenerated>:1)	JMP	602
	0x004f 00079 (<autogenerated>:1)	MOVQ	""..this+296(SP), AX
	0x0057 00087 (<autogenerated>:1)	TESTB	AL, (AX)
	0x0059 00089 (<autogenerated>:1)	MOVQ	(AX), CX
	0x005c 00092 (<autogenerated>:1)	MOVQ	8(AX), DX
	0x0060 00096 (<autogenerated>:1)	MOVQ	16(AX), AX
	0x0064 00100 (<autogenerated>:1)	MOVQ	CX, "".p+232(SP)
	0x006c 00108 (<autogenerated>:1)	MOVQ	DX, "".p+240(SP)
	0x0074 00116 (<autogenerated>:1)	MOVQ	AX, "".p+248(SP)
	0x007c 00124 (<unknown line number>)	NOP
	0x007c 00124 (main.go:32)	MOVQ	CX, (SP)
	0x0080 00128 (main.go:32)	MOVQ	DX, 8(SP)
	0x0085 00133 (main.go:32)	PCDATA	$1, $1
	0x0085 00133 (main.go:32)	CALL	runtime.convTstring(SB)
	0x008a 00138 (main.go:32)	MOVQ	16(SP), AX
	0x008f 00143 (main.go:32)	MOVQ	AX, ""..autotmp_12+112(SP)
	0x0094 00148 (main.go:32)	LEAQ	type.string(SB), CX
	0x009b 00155 (main.go:32)	MOVQ	CX, ""..autotmp_11+200(SP)
	0x00a3 00163 (main.go:32)	MOVQ	AX, ""..autotmp_11+208(SP)
	0x00ab 00171 (main.go:32)	LEAQ	go.string."I am coding %s language\n"(SB), AX
	0x00b2 00178 (main.go:32)	MOVQ	AX, fmt.format+136(SP)
	0x00ba 00186 (main.go:32)	MOVQ	$24, fmt.format+144(SP)
	0x00c6 00198 (main.go:32)	MOVQ	""..autotmp_11+200(SP), AX
	0x00ce 00206 (main.go:32)	MOVQ	""..autotmp_11+208(SP), CX
	0x00d6 00214 (main.go:32)	MOVQ	AX, "".~arg1+120(SP)
	0x00db 00219 (main.go:32)	MOVQ	CX, "".~arg1+128(SP)
	0x00e3 00227 (main.go:32)	XORPS	X0, X0
	0x00e6 00230 (main.go:32)	MOVUPS	X0, ""..autotmp_15+184(SP)
	0x00ee 00238 (main.go:32)	LEAQ	""..autotmp_15+184(SP), AX
	0x00f6 00246 (main.go:32)	MOVQ	AX, ""..autotmp_13+104(SP)
	0x00fb 00251 (main.go:32)	TESTB	AL, (AX)
	0x00fd 00253 (main.go:32)	MOVQ	"".~arg1+120(SP), CX
	0x0102 00258 (main.go:32)	MOVQ	"".~arg1+128(SP), DX
	0x010a 00266 (main.go:32)	MOVQ	CX, ""..autotmp_15+184(SP)
	0x0112 00274 (main.go:32)	MOVQ	DX, ""..autotmp_15+192(SP)
	0x011a 00282 (main.go:32)	TESTB	AL, (AX)
	0x011c 00284 (main.go:32)	JMP	286
	0x011e 00286 (main.go:32)	MOVQ	AX, fmt.a+256(SP)
	0x0126 00294 (main.go:32)	MOVQ	$1, fmt.a+264(SP)
	0x0132 00306 (main.go:32)	MOVQ	$1, fmt.a+272(SP)
	0x013e 00318 (main.go:32)	MOVQ	$0, fmt.n+80(SP)
	0x0147 00327 (main.go:32)	XORPS	X0, X0
	0x014a 00330 (main.go:32)	MOVUPS	X0, fmt.err+152(SP)
	0x0152 00338 (<unknown line number>)	NOP
	0x0152 00338 (main.go:32)	MOVQ	$0, fmt..autotmp_4+96(SP)
	0x015b 00347 (main.go:32)	XORPS	X0, X0
	0x015e 00350 (main.go:32)	MOVUPS	X0, fmt..autotmp_5+168(SP)
	0x0166 00358 ($GOROOT/src/fmt/print.go:213)	XORPS	X0, X0
	0x0169 00361 ($GOROOT/src/fmt/print.go:213)	MOVUPS	X0, ""..autotmp_10+216(SP)
	0x0171 00369 ($GOROOT/src/fmt/print.go:213)	MOVQ	os.Stdout(SB), AX
	0x0178 00376 ($GOROOT/src/fmt/print.go:213)	LEAQ	go.itab.*os.File,io.Writer(SB), CX
	0x017f 00383 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, (SP)
	0x0183 00387 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, 8(SP)
	0x0188 00392 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.format+136(SP), AX
	0x0190 00400 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.format+144(SP), CX
	0x0198 00408 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, 16(SP)
	0x019d 00413 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, 24(SP)
	0x01a2 00418 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.a+256(SP), AX
	0x01aa 00426 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.a+264(SP), CX
	0x01b2 00434 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.a+272(SP), DX
	0x01ba 00442 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, 32(SP)
	0x01bf 00447 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, 40(SP)
	0x01c4 00452 ($GOROOT/src/fmt/print.go:213)	MOVQ	DX, 48(SP)
	0x01c9 00457 ($GOROOT/src/fmt/print.go:213)	CALL	fmt.Fprintf(SB)
	0x01ce 00462 ($GOROOT/src/fmt/print.go:213)	MOVQ	56(SP), AX
	0x01d3 00467 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, ""..autotmp_9+88(SP)
	0x01d8 00472 ($GOROOT/src/fmt/print.go:213)	MOVQ	64(SP), AX
	0x01dd 00477 ($GOROOT/src/fmt/print.go:213)	MOVQ	72(SP), CX
	0x01e2 00482 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, ""..autotmp_10+216(SP)
	0x01ea 00490 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, ""..autotmp_10+224(SP)
	0x01f2 00498 ($GOROOT/src/fmt/print.go:213)	MOVQ	""..autotmp_9+88(SP), AX
	0x01f7 00503 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, fmt..autotmp_4+96(SP)
	0x01fc 00508 ($GOROOT/src/fmt/print.go:213)	MOVQ	""..autotmp_10+216(SP), AX
	0x0204 00516 ($GOROOT/src/fmt/print.go:213)	MOVQ	""..autotmp_10+224(SP), CX
	0x020c 00524 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, fmt..autotmp_5+168(SP)
	0x0214 00532 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, fmt..autotmp_5+176(SP)
	0x021c 00540 (main.go:32)	MOVQ	fmt..autotmp_4+96(SP), AX
	0x0221 00545 (main.go:32)	MOVQ	AX, fmt.n+80(SP)
	0x0226 00550 (main.go:32)	MOVQ	fmt..autotmp_5+168(SP), AX
	0x022e 00558 (main.go:32)	MOVQ	fmt..autotmp_5+176(SP), CX
	0x0236 00566 (main.go:32)	MOVQ	AX, fmt.err+152(SP)
	0x023e 00574 (main.go:32)	MOVQ	CX, fmt.err+160(SP)
	0x0246 00582 (main.go:32)	JMP	584
	0x0248 00584 (main.go:32)	PCDATA	$1, $-1
	0x0248 00584 (main.go:32)	JMP	586
	0x024a 00586 (main.go:32)	MOVQ	280(SP), BP
	0x0252 00594 (main.go:32)	ADDQ	$288, SP
	0x0259 00601 (main.go:32)	RET
	0x025a 00602 (<autogenerated>:1)	PCDATA	$1, $1
	0x025a 00602 (<autogenerated>:1)	CALL	runtime.panicwrap(SB)
	0x025f 00607 (<autogenerated>:1)	XCHGL	AX, AX
	0x0260 00608 (<autogenerated>:1)	NOP
	0x0260 00608 (<autogenerated>:1)	PCDATA	$1, $-1
	0x0260 00608 (<autogenerated>:1)	PCDATA	$0, $-2
	0x0260 00608 (<autogenerated>:1)	CALL	runtime.morestack_noctxt(SB)
	0x0265 00613 (<autogenerated>:1)	PCDATA	$0, $-1
	0x0265 00613 (<autogenerated>:1)	JMP	0
	0x026a 00618 (<autogenerated>:1)	LEAQ	296(SP), DI
	0x0272 00626 (<autogenerated>:1)	CMPQ	(BX), DI
	0x0275 00629 (<autogenerated>:1)	JNE	63
	0x027b 00635 (<autogenerated>:1)	MOVQ	SP, (BX)
	0x027e 00638 (<autogenerated>:1)	NOP
	0x0280 00640 (<autogenerated>:1)	JMP	63
	0x0000 65 48 8b 0c 25 00 00 00 00 48 8d 84 24 60 ff ff  eH..%....H..$`..
	0x0010 ff 48 3b 41 10 0f 86 45 02 00 00 48 81 ec 20 01  .H;A...E...H.. .
	0x0020 00 00 48 89 ac 24 18 01 00 00 48 8d ac 24 18 01  ..H..$....H..$..
	0x0030 00 00 48 8b 59 20 48 85 db 0f 85 2b 02 00 00 48  ..H.Y H....+...H
	0x0040 83 bc 24 28 01 00 00 00 75 05 e9 0b 02 00 00 48  ..$(....u......H
	0x0050 8b 84 24 28 01 00 00 84 00 48 8b 08 48 8b 50 08  ..$(.....H..H.P.
	0x0060 48 8b 40 10 48 89 8c 24 e8 00 00 00 48 89 94 24  H.@.H..$....H..$
	0x0070 f0 00 00 00 48 89 84 24 f8 00 00 00 48 89 0c 24  ....H..$....H..$
	0x0080 48 89 54 24 08 e8 00 00 00 00 48 8b 44 24 10 48  H.T$......H.D$.H
	0x0090 89 44 24 70 48 8d 0d 00 00 00 00 48 89 8c 24 c8  .D$pH......H..$.
	0x00a0 00 00 00 48 89 84 24 d0 00 00 00 48 8d 05 00 00  ...H..$....H....
	0x00b0 00 00 48 89 84 24 88 00 00 00 48 c7 84 24 90 00  ..H..$....H..$..
	0x00c0 00 00 18 00 00 00 48 8b 84 24 c8 00 00 00 48 8b  ......H..$....H.
	0x00d0 8c 24 d0 00 00 00 48 89 44 24 78 48 89 8c 24 80  .$....H.D$xH..$.
	0x00e0 00 00 00 0f 57 c0 0f 11 84 24 b8 00 00 00 48 8d  ....W....$....H.
	0x00f0 84 24 b8 00 00 00 48 89 44 24 68 84 00 48 8b 4c  .$....H.D$h..H.L
	0x0100 24 78 48 8b 94 24 80 00 00 00 48 89 8c 24 b8 00  $xH..$....H..$..
	0x0110 00 00 48 89 94 24 c0 00 00 00 84 00 eb 00 48 89  ..H..$........H.
	0x0120 84 24 00 01 00 00 48 c7 84 24 08 01 00 00 01 00  .$....H..$......
	0x0130 00 00 48 c7 84 24 10 01 00 00 01 00 00 00 48 c7  ..H..$........H.
	0x0140 44 24 50 00 00 00 00 0f 57 c0 0f 11 84 24 98 00  D$P.....W....$..
	0x0150 00 00 48 c7 44 24 60 00 00 00 00 0f 57 c0 0f 11  ..H.D$`.....W...
	0x0160 84 24 a8 00 00 00 0f 57 c0 0f 11 84 24 d8 00 00  .$.....W....$...
	0x0170 00 48 8b 05 00 00 00 00 48 8d 0d 00 00 00 00 48  .H......H......H
	0x0180 89 0c 24 48 89 44 24 08 48 8b 84 24 88 00 00 00  ..$H.D$.H..$....
	0x0190 48 8b 8c 24 90 00 00 00 48 89 44 24 10 48 89 4c  H..$....H.D$.H.L
	0x01a0 24 18 48 8b 84 24 00 01 00 00 48 8b 8c 24 08 01  $.H..$....H..$..
	0x01b0 00 00 48 8b 94 24 10 01 00 00 48 89 44 24 20 48  ..H..$....H.D$ H
	0x01c0 89 4c 24 28 48 89 54 24 30 e8 00 00 00 00 48 8b  .L$(H.T$0.....H.
	0x01d0 44 24 38 48 89 44 24 58 48 8b 44 24 40 48 8b 4c  D$8H.D$XH.D$@H.L
	0x01e0 24 48 48 89 84 24 d8 00 00 00 48 89 8c 24 e0 00  $HH..$....H..$..
	0x01f0 00 00 48 8b 44 24 58 48 89 44 24 60 48 8b 84 24  ..H.D$XH.D$`H..$
	0x0200 d8 00 00 00 48 8b 8c 24 e0 00 00 00 48 89 84 24  ....H..$....H..$
	0x0210 a8 00 00 00 48 89 8c 24 b0 00 00 00 48 8b 44 24  ....H..$....H.D$
	0x0220 60 48 89 44 24 50 48 8b 84 24 a8 00 00 00 48 8b  `H.D$PH..$....H.
	0x0230 8c 24 b0 00 00 00 48 89 84 24 98 00 00 00 48 89  .$....H..$....H.
	0x0240 8c 24 a0 00 00 00 eb 00 eb 00 48 8b ac 24 18 01  .$........H..$..
	0x0250 00 00 48 81 c4 20 01 00 00 c3 e8 00 00 00 00 90  ..H.. ..........
	0x0260 e8 00 00 00 00 e9 96 fd ff ff 48 8d bc 24 28 01  ..........H..$(.
	0x0270 00 00 48 39 3b 0f 85 c4 fd ff ff 48 89 23 66 90  ..H9;......H.#f.
	0x0280 e9 ba fd ff ff                                   .....
	rel 5+4 t=17 TLS+0
	rel 134+4 t=8 runtime.convTstring+0
	rel 151+4 t=16 type.string+0
	rel 174+4 t=16 go.string."I am coding %s language\n"+0
	rel 372+4 t=16 os.Stdout+0
	rel 379+4 t=16 go.itab.*os.File,io.Writer+0
	rel 458+4 t=8 fmt.Fprintf+0
	rel 603+4 t=8 runtime.panicwrap+0
	rel 609+4 t=8 runtime.morestack_noctxt+0
"".(*Gopher).debug STEXT dupok size=645 args=0x8 locals=0x120
	0x0000 00000 (<autogenerated>:1)	TEXT	"".(*Gopher).debug(SB), DUPOK|WRAPPER|ABIInternal, $288-8
	0x0000 00000 (<autogenerated>:1)	MOVQ	(TLS), CX
	0x0009 00009 (<autogenerated>:1)	LEAQ	-160(SP), AX
	0x0011 00017 (<autogenerated>:1)	CMPQ	AX, 16(CX)
	0x0015 00021 (<autogenerated>:1)	PCDATA	$0, $-2
	0x0015 00021 (<autogenerated>:1)	JLS	608
	0x001b 00027 (<autogenerated>:1)	PCDATA	$0, $-1
	0x001b 00027 (<autogenerated>:1)	SUBQ	$288, SP
	0x0022 00034 (<autogenerated>:1)	MOVQ	BP, 280(SP)
	0x002a 00042 (<autogenerated>:1)	LEAQ	280(SP), BP
	0x0032 00050 (<autogenerated>:1)	MOVQ	32(CX), BX
	0x0036 00054 (<autogenerated>:1)	TESTQ	BX, BX
	0x0039 00057 (<autogenerated>:1)	JNE	618
	0x003f 00063 (<autogenerated>:1)	NOP
	0x003f 00063 (<autogenerated>:1)	FUNCDATA	$0, gclocals·1a65e721a2ccc325b382662e7ffee780(SB)
	0x003f 00063 (<autogenerated>:1)	FUNCDATA	$1, gclocals·000713d0e9e44438ca2d32aa6561c14c(SB)
	0x003f 00063 (<autogenerated>:1)	FUNCDATA	$3, "".(*Gopher).debug.stkobj(SB)
	0x003f 00063 (<autogenerated>:1)	CMPQ	""..this+296(SP), $0
	0x0048 00072 (<autogenerated>:1)	JNE	79
	0x004a 00074 (<autogenerated>:1)	JMP	602
	0x004f 00079 (<autogenerated>:1)	MOVQ	""..this+296(SP), AX
	0x0057 00087 (<autogenerated>:1)	TESTB	AL, (AX)
	0x0059 00089 (<autogenerated>:1)	MOVQ	(AX), CX
	0x005c 00092 (<autogenerated>:1)	MOVQ	8(AX), DX
	0x0060 00096 (<autogenerated>:1)	MOVQ	16(AX), AX
	0x0064 00100 (<autogenerated>:1)	MOVQ	CX, "".p+232(SP)
	0x006c 00108 (<autogenerated>:1)	MOVQ	DX, "".p+240(SP)
	0x0074 00116 (<autogenerated>:1)	MOVQ	AX, "".p+248(SP)
	0x007c 00124 (<unknown line number>)	NOP
	0x007c 00124 (main.go:36)	MOVQ	CX, (SP)
	0x0080 00128 (main.go:36)	MOVQ	DX, 8(SP)
	0x0085 00133 (main.go:36)	PCDATA	$1, $1
	0x0085 00133 (main.go:36)	CALL	runtime.convTstring(SB)
	0x008a 00138 (main.go:36)	MOVQ	16(SP), AX
	0x008f 00143 (main.go:36)	MOVQ	AX, ""..autotmp_12+112(SP)
	0x0094 00148 (main.go:36)	LEAQ	type.string(SB), CX
	0x009b 00155 (main.go:36)	MOVQ	CX, ""..autotmp_11+200(SP)
	0x00a3 00163 (main.go:36)	MOVQ	AX, ""..autotmp_11+208(SP)
	0x00ab 00171 (main.go:36)	LEAQ	go.string."I am debuging %s language\n"(SB), AX
	0x00b2 00178 (main.go:36)	MOVQ	AX, fmt.format+136(SP)
	0x00ba 00186 (main.go:36)	MOVQ	$26, fmt.format+144(SP)
	0x00c6 00198 (main.go:36)	MOVQ	""..autotmp_11+200(SP), AX
	0x00ce 00206 (main.go:36)	MOVQ	""..autotmp_11+208(SP), CX
	0x00d6 00214 (main.go:36)	MOVQ	AX, "".~arg1+120(SP)
	0x00db 00219 (main.go:36)	MOVQ	CX, "".~arg1+128(SP)
	0x00e3 00227 (main.go:36)	XORPS	X0, X0
	0x00e6 00230 (main.go:36)	MOVUPS	X0, ""..autotmp_15+184(SP)
	0x00ee 00238 (main.go:36)	LEAQ	""..autotmp_15+184(SP), AX
	0x00f6 00246 (main.go:36)	MOVQ	AX, ""..autotmp_13+104(SP)
	0x00fb 00251 (main.go:36)	TESTB	AL, (AX)
	0x00fd 00253 (main.go:36)	MOVQ	"".~arg1+120(SP), CX
	0x0102 00258 (main.go:36)	MOVQ	"".~arg1+128(SP), DX
	0x010a 00266 (main.go:36)	MOVQ	CX, ""..autotmp_15+184(SP)
	0x0112 00274 (main.go:36)	MOVQ	DX, ""..autotmp_15+192(SP)
	0x011a 00282 (main.go:36)	TESTB	AL, (AX)
	0x011c 00284 (main.go:36)	JMP	286
	0x011e 00286 (main.go:36)	MOVQ	AX, fmt.a+256(SP)
	0x0126 00294 (main.go:36)	MOVQ	$1, fmt.a+264(SP)
	0x0132 00306 (main.go:36)	MOVQ	$1, fmt.a+272(SP)
	0x013e 00318 (main.go:36)	MOVQ	$0, fmt.n+80(SP)
	0x0147 00327 (main.go:36)	XORPS	X0, X0
	0x014a 00330 (main.go:36)	MOVUPS	X0, fmt.err+152(SP)
	0x0152 00338 (<unknown line number>)	NOP
	0x0152 00338 (main.go:32)	MOVQ	$0, fmt..autotmp_4+96(SP)
	0x015b 00347 (main.go:32)	XORPS	X0, X0
	0x015e 00350 (main.go:32)	MOVUPS	X0, fmt..autotmp_5+168(SP)
	0x0166 00358 ($GOROOT/src/fmt/print.go:213)	XORPS	X0, X0
	0x0169 00361 ($GOROOT/src/fmt/print.go:213)	MOVUPS	X0, ""..autotmp_10+216(SP)
	0x0171 00369 ($GOROOT/src/fmt/print.go:213)	MOVQ	os.Stdout(SB), AX
	0x0178 00376 ($GOROOT/src/fmt/print.go:213)	LEAQ	go.itab.*os.File,io.Writer(SB), CX
	0x017f 00383 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, (SP)
	0x0183 00387 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, 8(SP)
	0x0188 00392 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.format+136(SP), AX
	0x0190 00400 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.format+144(SP), CX
	0x0198 00408 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, 16(SP)
	0x019d 00413 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, 24(SP)
	0x01a2 00418 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.a+256(SP), AX
	0x01aa 00426 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.a+264(SP), CX
	0x01b2 00434 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.a+272(SP), DX
	0x01ba 00442 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, 32(SP)
	0x01bf 00447 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, 40(SP)
	0x01c4 00452 ($GOROOT/src/fmt/print.go:213)	MOVQ	DX, 48(SP)
	0x01c9 00457 ($GOROOT/src/fmt/print.go:213)	CALL	fmt.Fprintf(SB)
	0x01ce 00462 ($GOROOT/src/fmt/print.go:213)	MOVQ	56(SP), AX
	0x01d3 00467 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, ""..autotmp_9+88(SP)
	0x01d8 00472 ($GOROOT/src/fmt/print.go:213)	MOVQ	64(SP), AX
	0x01dd 00477 ($GOROOT/src/fmt/print.go:213)	MOVQ	72(SP), CX
	0x01e2 00482 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, ""..autotmp_10+216(SP)
	0x01ea 00490 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, ""..autotmp_10+224(SP)
	0x01f2 00498 ($GOROOT/src/fmt/print.go:213)	MOVQ	""..autotmp_9+88(SP), AX
	0x01f7 00503 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, fmt..autotmp_4+96(SP)
	0x01fc 00508 ($GOROOT/src/fmt/print.go:213)	MOVQ	""..autotmp_10+216(SP), AX
	0x0204 00516 ($GOROOT/src/fmt/print.go:213)	MOVQ	""..autotmp_10+224(SP), CX
	0x020c 00524 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, fmt..autotmp_5+168(SP)
	0x0214 00532 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, fmt..autotmp_5+176(SP)
	0x021c 00540 (main.go:36)	MOVQ	fmt..autotmp_4+96(SP), AX
	0x0221 00545 (main.go:36)	MOVQ	AX, fmt.n+80(SP)
	0x0226 00550 (main.go:36)	MOVQ	fmt..autotmp_5+168(SP), AX
	0x022e 00558 (main.go:36)	MOVQ	fmt..autotmp_5+176(SP), CX
	0x0236 00566 (main.go:36)	MOVQ	AX, fmt.err+152(SP)
	0x023e 00574 (main.go:36)	MOVQ	CX, fmt.err+160(SP)
	0x0246 00582 (main.go:36)	JMP	584
	0x0248 00584 (main.go:36)	PCDATA	$1, $-1
	0x0248 00584 (main.go:36)	JMP	586
	0x024a 00586 (main.go:36)	MOVQ	280(SP), BP
	0x0252 00594 (main.go:36)	ADDQ	$288, SP
	0x0259 00601 (main.go:36)	RET
	0x025a 00602 (<autogenerated>:1)	PCDATA	$1, $1
	0x025a 00602 (<autogenerated>:1)	CALL	runtime.panicwrap(SB)
	0x025f 00607 (<autogenerated>:1)	XCHGL	AX, AX
	0x0260 00608 (<autogenerated>:1)	NOP
	0x0260 00608 (<autogenerated>:1)	PCDATA	$1, $-1
	0x0260 00608 (<autogenerated>:1)	PCDATA	$0, $-2
	0x0260 00608 (<autogenerated>:1)	CALL	runtime.morestack_noctxt(SB)
	0x0265 00613 (<autogenerated>:1)	PCDATA	$0, $-1
	0x0265 00613 (<autogenerated>:1)	JMP	0
	0x026a 00618 (<autogenerated>:1)	LEAQ	296(SP), DI
	0x0272 00626 (<autogenerated>:1)	CMPQ	(BX), DI
	0x0275 00629 (<autogenerated>:1)	JNE	63
	0x027b 00635 (<autogenerated>:1)	MOVQ	SP, (BX)
	0x027e 00638 (<autogenerated>:1)	NOP
	0x0280 00640 (<autogenerated>:1)	JMP	63
	0x0000 65 48 8b 0c 25 00 00 00 00 48 8d 84 24 60 ff ff  eH..%....H..$`..
	0x0010 ff 48 3b 41 10 0f 86 45 02 00 00 48 81 ec 20 01  .H;A...E...H.. .
	0x0020 00 00 48 89 ac 24 18 01 00 00 48 8d ac 24 18 01  ..H..$....H..$..
	0x0030 00 00 48 8b 59 20 48 85 db 0f 85 2b 02 00 00 48  ..H.Y H....+...H
	0x0040 83 bc 24 28 01 00 00 00 75 05 e9 0b 02 00 00 48  ..$(....u......H
	0x0050 8b 84 24 28 01 00 00 84 00 48 8b 08 48 8b 50 08  ..$(.....H..H.P.
	0x0060 48 8b 40 10 48 89 8c 24 e8 00 00 00 48 89 94 24  H.@.H..$....H..$
	0x0070 f0 00 00 00 48 89 84 24 f8 00 00 00 48 89 0c 24  ....H..$....H..$
	0x0080 48 89 54 24 08 e8 00 00 00 00 48 8b 44 24 10 48  H.T$......H.D$.H
	0x0090 89 44 24 70 48 8d 0d 00 00 00 00 48 89 8c 24 c8  .D$pH......H..$.
	0x00a0 00 00 00 48 89 84 24 d0 00 00 00 48 8d 05 00 00  ...H..$....H....
	0x00b0 00 00 48 89 84 24 88 00 00 00 48 c7 84 24 90 00  ..H..$....H..$..
	0x00c0 00 00 1a 00 00 00 48 8b 84 24 c8 00 00 00 48 8b  ......H..$....H.
	0x00d0 8c 24 d0 00 00 00 48 89 44 24 78 48 89 8c 24 80  .$....H.D$xH..$.
	0x00e0 00 00 00 0f 57 c0 0f 11 84 24 b8 00 00 00 48 8d  ....W....$....H.
	0x00f0 84 24 b8 00 00 00 48 89 44 24 68 84 00 48 8b 4c  .$....H.D$h..H.L
	0x0100 24 78 48 8b 94 24 80 00 00 00 48 89 8c 24 b8 00  $xH..$....H..$..
	0x0110 00 00 48 89 94 24 c0 00 00 00 84 00 eb 00 48 89  ..H..$........H.
	0x0120 84 24 00 01 00 00 48 c7 84 24 08 01 00 00 01 00  .$....H..$......
	0x0130 00 00 48 c7 84 24 10 01 00 00 01 00 00 00 48 c7  ..H..$........H.
	0x0140 44 24 50 00 00 00 00 0f 57 c0 0f 11 84 24 98 00  D$P.....W....$..
	0x0150 00 00 48 c7 44 24 60 00 00 00 00 0f 57 c0 0f 11  ..H.D$`.....W...
	0x0160 84 24 a8 00 00 00 0f 57 c0 0f 11 84 24 d8 00 00  .$.....W....$...
	0x0170 00 48 8b 05 00 00 00 00 48 8d 0d 00 00 00 00 48  .H......H......H
	0x0180 89 0c 24 48 89 44 24 08 48 8b 84 24 88 00 00 00  ..$H.D$.H..$....
	0x0190 48 8b 8c 24 90 00 00 00 48 89 44 24 10 48 89 4c  H..$....H.D$.H.L
	0x01a0 24 18 48 8b 84 24 00 01 00 00 48 8b 8c 24 08 01  $.H..$....H..$..
	0x01b0 00 00 48 8b 94 24 10 01 00 00 48 89 44 24 20 48  ..H..$....H.D$ H
	0x01c0 89 4c 24 28 48 89 54 24 30 e8 00 00 00 00 48 8b  .L$(H.T$0.....H.
	0x01d0 44 24 38 48 89 44 24 58 48 8b 44 24 40 48 8b 4c  D$8H.D$XH.D$@H.L
	0x01e0 24 48 48 89 84 24 d8 00 00 00 48 89 8c 24 e0 00  $HH..$....H..$..
	0x01f0 00 00 48 8b 44 24 58 48 89 44 24 60 48 8b 84 24  ..H.D$XH.D$`H..$
	0x0200 d8 00 00 00 48 8b 8c 24 e0 00 00 00 48 89 84 24  ....H..$....H..$
	0x0210 a8 00 00 00 48 89 8c 24 b0 00 00 00 48 8b 44 24  ....H..$....H.D$
	0x0220 60 48 89 44 24 50 48 8b 84 24 a8 00 00 00 48 8b  `H.D$PH..$....H.
	0x0230 8c 24 b0 00 00 00 48 89 84 24 98 00 00 00 48 89  .$....H..$....H.
	0x0240 8c 24 a0 00 00 00 eb 00 eb 00 48 8b ac 24 18 01  .$........H..$..
	0x0250 00 00 48 81 c4 20 01 00 00 c3 e8 00 00 00 00 90  ..H.. ..........
	0x0260 e8 00 00 00 00 e9 96 fd ff ff 48 8d bc 24 28 01  ..........H..$(.
	0x0270 00 00 48 39 3b 0f 85 c4 fd ff ff 48 89 23 66 90  ..H9;......H.#f.
	0x0280 e9 ba fd ff ff                                   .....
	rel 5+4 t=17 TLS+0
	rel 134+4 t=8 runtime.convTstring+0
	rel 151+4 t=16 type.string+0
	rel 174+4 t=16 go.string."I am debuging %s language\n"+0
	rel 372+4 t=16 os.Stdout+0
	rel 379+4 t=16 go.itab.*os.File,io.Writer+0
	rel 458+4 t=8 fmt.Fprintf+0
	rel 603+4 t=8 runtime.panicwrap+0
	rel 609+4 t=8 runtime.morestack_noctxt+0
"".Gopher.code STEXT size=554 args=0x18 locals=0x108
	0x0000 00000 (main.go:31)	TEXT	"".Gopher.code(SB), ABIInternal, $264-24
	0x0000 00000 (main.go:31)	MOVQ	(TLS), CX
	0x0009 00009 (main.go:31)	LEAQ	-136(SP), AX
	0x0011 00017 (main.go:31)	CMPQ	AX, 16(CX)
	0x0015 00021 (main.go:31)	PCDATA	$0, $-2
	0x0015 00021 (main.go:31)	JLS	544
	0x001b 00027 (main.go:31)	PCDATA	$0, $-1
	0x001b 00027 (main.go:31)	SUBQ	$264, SP
	0x0022 00034 (main.go:31)	MOVQ	BP, 256(SP)
	0x002a 00042 (main.go:31)	LEAQ	256(SP), BP
	0x0032 00050 (main.go:31)	FUNCDATA	$0, gclocals·1a65e721a2ccc325b382662e7ffee780(SB)
	0x0032 00050 (main.go:31)	FUNCDATA	$1, gclocals·0c390dd2b680890c3ee1eb04d3729d9e(SB)
	0x0032 00050 (main.go:31)	FUNCDATA	$3, "".Gopher.code.stkobj(SB)
	0x0032 00050 (main.go:32)	MOVQ	"".p+272(SP), AX
	0x003a 00058 (main.go:32)	MOVQ	"".p+280(SP), CX
	0x0042 00066 (main.go:32)	MOVQ	AX, (SP)
	0x0046 00070 (main.go:32)	MOVQ	CX, 8(SP)
	0x004b 00075 (main.go:32)	PCDATA	$1, $1
	0x004b 00075 (main.go:32)	CALL	runtime.convTstring(SB)
	0x0050 00080 (main.go:32)	MOVQ	16(SP), AX
	0x0055 00085 (main.go:32)	MOVQ	AX, ""..autotmp_11+112(SP)
	0x005a 00090 (main.go:32)	LEAQ	type.string(SB), CX
	0x0061 00097 (main.go:32)	MOVQ	CX, ""..autotmp_10+216(SP)
	0x0069 00105 (main.go:32)	MOVQ	AX, ""..autotmp_10+224(SP)
	0x0071 00113 (main.go:32)	LEAQ	go.string."I am coding %s language\n"(SB), AX
	0x0078 00120 (main.go:32)	MOVQ	AX, fmt.format+136(SP)
	0x0080 00128 (main.go:32)	MOVQ	$24, fmt.format+144(SP)
	0x008c 00140 (main.go:32)	MOVQ	""..autotmp_10+216(SP), AX
	0x0094 00148 (main.go:32)	MOVQ	""..autotmp_10+224(SP), CX
	0x009c 00156 (main.go:32)	MOVQ	AX, "".~arg1+120(SP)
	0x00a1 00161 (main.go:32)	MOVQ	CX, "".~arg1+128(SP)
	0x00a9 00169 (main.go:32)	XORPS	X0, X0
	0x00ac 00172 (main.go:32)	MOVUPS	X0, ""..autotmp_14+200(SP)
	0x00b4 00180 (main.go:32)	LEAQ	""..autotmp_14+200(SP), AX
	0x00bc 00188 (main.go:32)	MOVQ	AX, ""..autotmp_12+104(SP)
	0x00c1 00193 (main.go:32)	TESTB	AL, (AX)
	0x00c3 00195 (main.go:32)	MOVQ	"".~arg1+120(SP), CX
	0x00c8 00200 (main.go:32)	MOVQ	"".~arg1+128(SP), DX
	0x00d0 00208 (main.go:32)	MOVQ	CX, ""..autotmp_14+200(SP)
	0x00d8 00216 (main.go:32)	MOVQ	DX, ""..autotmp_14+208(SP)
	0x00e0 00224 (main.go:32)	TESTB	AL, (AX)
	0x00e2 00226 (main.go:32)	JMP	228
	0x00e4 00228 (main.go:32)	MOVQ	AX, fmt.a+232(SP)
	0x00ec 00236 (main.go:32)	MOVQ	$1, fmt.a+240(SP)
	0x00f8 00248 (main.go:32)	MOVQ	$1, fmt.a+248(SP)
	0x0104 00260 (main.go:32)	MOVQ	$0, fmt.n+80(SP)
	0x010d 00269 (main.go:32)	XORPS	X0, X0
	0x0110 00272 (main.go:32)	MOVUPS	X0, fmt.err+152(SP)
	0x0118 00280 (<unknown line number>)	NOP
	0x0118 00280 (main.go:32)	MOVQ	$0, fmt..autotmp_4+96(SP)
	0x0121 00289 (main.go:32)	XORPS	X0, X0
	0x0124 00292 (main.go:32)	MOVUPS	X0, fmt..autotmp_5+184(SP)
	0x012c 00300 ($GOROOT/src/fmt/print.go:213)	XORPS	X0, X0
	0x012f 00303 ($GOROOT/src/fmt/print.go:213)	MOVUPS	X0, ""..autotmp_9+168(SP)
	0x0137 00311 ($GOROOT/src/fmt/print.go:213)	MOVQ	os.Stdout(SB), AX
	0x013e 00318 ($GOROOT/src/fmt/print.go:213)	LEAQ	go.itab.*os.File,io.Writer(SB), CX
	0x0145 00325 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, (SP)
	0x0149 00329 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, 8(SP)
	0x014e 00334 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.format+136(SP), AX
	0x0156 00342 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.format+144(SP), CX
	0x015e 00350 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, 16(SP)
	0x0163 00355 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, 24(SP)
	0x0168 00360 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.a+232(SP), AX
	0x0170 00368 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.a+240(SP), CX
	0x0178 00376 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.a+248(SP), DX
	0x0180 00384 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, 32(SP)
	0x0185 00389 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, 40(SP)
	0x018a 00394 ($GOROOT/src/fmt/print.go:213)	MOVQ	DX, 48(SP)
	0x018f 00399 ($GOROOT/src/fmt/print.go:213)	CALL	fmt.Fprintf(SB)
	0x0194 00404 ($GOROOT/src/fmt/print.go:213)	MOVQ	56(SP), AX
	0x0199 00409 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, ""..autotmp_8+88(SP)
	0x019e 00414 ($GOROOT/src/fmt/print.go:213)	MOVQ	64(SP), AX
	0x01a3 00419 ($GOROOT/src/fmt/print.go:213)	MOVQ	72(SP), CX
	0x01a8 00424 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, ""..autotmp_9+168(SP)
	0x01b0 00432 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, ""..autotmp_9+176(SP)
	0x01b8 00440 ($GOROOT/src/fmt/print.go:213)	MOVQ	""..autotmp_8+88(SP), AX
	0x01bd 00445 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, fmt..autotmp_4+96(SP)
	0x01c2 00450 ($GOROOT/src/fmt/print.go:213)	MOVQ	""..autotmp_9+168(SP), AX
	0x01ca 00458 ($GOROOT/src/fmt/print.go:213)	MOVQ	""..autotmp_9+176(SP), CX
	0x01d2 00466 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, fmt..autotmp_5+184(SP)
	0x01da 00474 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, fmt..autotmp_5+192(SP)
	0x01e2 00482 (main.go:32)	MOVQ	fmt..autotmp_4+96(SP), AX
	0x01e7 00487 (main.go:32)	MOVQ	AX, fmt.n+80(SP)
	0x01ec 00492 (main.go:32)	MOVQ	fmt..autotmp_5+184(SP), AX
	0x01f4 00500 (main.go:32)	MOVQ	fmt..autotmp_5+192(SP), CX
	0x01fc 00508 (main.go:32)	MOVQ	AX, fmt.err+152(SP)
	0x0204 00516 (main.go:32)	MOVQ	CX, fmt.err+160(SP)
	0x020c 00524 (main.go:32)	JMP	526
	0x020e 00526 (main.go:32)	PCDATA	$1, $-1
	0x020e 00526 (main.go:32)	MOVQ	256(SP), BP
	0x0216 00534 (main.go:32)	ADDQ	$264, SP
	0x021d 00541 (main.go:32)	RET
	0x021e 00542 (main.go:32)	NOP
	0x021e 00542 (main.go:31)	PCDATA	$1, $-1
	0x021e 00542 (main.go:31)	PCDATA	$0, $-2
	0x021e 00542 (main.go:31)	NOP
	0x0220 00544 (main.go:31)	CALL	runtime.morestack_noctxt(SB)
	0x0225 00549 (main.go:31)	PCDATA	$0, $-1
	0x0225 00549 (main.go:31)	JMP	0
	0x0000 65 48 8b 0c 25 00 00 00 00 48 8d 84 24 78 ff ff  eH..%....H..$x..
	0x0010 ff 48 3b 41 10 0f 86 05 02 00 00 48 81 ec 08 01  .H;A.......H....
	0x0020 00 00 48 89 ac 24 00 01 00 00 48 8d ac 24 00 01  ..H..$....H..$..
	0x0030 00 00 48 8b 84 24 10 01 00 00 48 8b 8c 24 18 01  ..H..$....H..$..
	0x0040 00 00 48 89 04 24 48 89 4c 24 08 e8 00 00 00 00  ..H..$H.L$......
	0x0050 48 8b 44 24 10 48 89 44 24 70 48 8d 0d 00 00 00  H.D$.H.D$pH.....
	0x0060 00 48 89 8c 24 d8 00 00 00 48 89 84 24 e0 00 00  .H..$....H..$...
	0x0070 00 48 8d 05 00 00 00 00 48 89 84 24 88 00 00 00  .H......H..$....
	0x0080 48 c7 84 24 90 00 00 00 18 00 00 00 48 8b 84 24  H..$........H..$
	0x0090 d8 00 00 00 48 8b 8c 24 e0 00 00 00 48 89 44 24  ....H..$....H.D$
	0x00a0 78 48 89 8c 24 80 00 00 00 0f 57 c0 0f 11 84 24  xH..$.....W....$
	0x00b0 c8 00 00 00 48 8d 84 24 c8 00 00 00 48 89 44 24  ....H..$....H.D$
	0x00c0 68 84 00 48 8b 4c 24 78 48 8b 94 24 80 00 00 00  h..H.L$xH..$....
	0x00d0 48 89 8c 24 c8 00 00 00 48 89 94 24 d0 00 00 00  H..$....H..$....
	0x00e0 84 00 eb 00 48 89 84 24 e8 00 00 00 48 c7 84 24  ....H..$....H..$
	0x00f0 f0 00 00 00 01 00 00 00 48 c7 84 24 f8 00 00 00  ........H..$....
	0x0100 01 00 00 00 48 c7 44 24 50 00 00 00 00 0f 57 c0  ....H.D$P.....W.
	0x0110 0f 11 84 24 98 00 00 00 48 c7 44 24 60 00 00 00  ...$....H.D$`...
	0x0120 00 0f 57 c0 0f 11 84 24 b8 00 00 00 0f 57 c0 0f  ..W....$.....W..
	0x0130 11 84 24 a8 00 00 00 48 8b 05 00 00 00 00 48 8d  ..$....H......H.
	0x0140 0d 00 00 00 00 48 89 0c 24 48 89 44 24 08 48 8b  .....H..$H.D$.H.
	0x0150 84 24 88 00 00 00 48 8b 8c 24 90 00 00 00 48 89  .$....H..$....H.
	0x0160 44 24 10 48 89 4c 24 18 48 8b 84 24 e8 00 00 00  D$.H.L$.H..$....
	0x0170 48 8b 8c 24 f0 00 00 00 48 8b 94 24 f8 00 00 00  H..$....H..$....
	0x0180 48 89 44 24 20 48 89 4c 24 28 48 89 54 24 30 e8  H.D$ H.L$(H.T$0.
	0x0190 00 00 00 00 48 8b 44 24 38 48 89 44 24 58 48 8b  ....H.D$8H.D$XH.
	0x01a0 44 24 40 48 8b 4c 24 48 48 89 84 24 a8 00 00 00  D$@H.L$HH..$....
	0x01b0 48 89 8c 24 b0 00 00 00 48 8b 44 24 58 48 89 44  H..$....H.D$XH.D
	0x01c0 24 60 48 8b 84 24 a8 00 00 00 48 8b 8c 24 b0 00  $`H..$....H..$..
	0x01d0 00 00 48 89 84 24 b8 00 00 00 48 89 8c 24 c0 00  ..H..$....H..$..
	0x01e0 00 00 48 8b 44 24 60 48 89 44 24 50 48 8b 84 24  ..H.D$`H.D$PH..$
	0x01f0 b8 00 00 00 48 8b 8c 24 c0 00 00 00 48 89 84 24  ....H..$....H..$
	0x0200 98 00 00 00 48 89 8c 24 a0 00 00 00 eb 00 48 8b  ....H..$......H.
	0x0210 ac 24 00 01 00 00 48 81 c4 08 01 00 00 c3 66 90  .$....H.......f.
	0x0220 e8 00 00 00 00 e9 d6 fd ff ff                    ..........
	rel 5+4 t=17 TLS+0
	rel 76+4 t=8 runtime.convTstring+0
	rel 93+4 t=16 type.string+0
	rel 116+4 t=16 go.string."I am coding %s language\n"+0
	rel 314+4 t=16 os.Stdout+0
	rel 321+4 t=16 go.itab.*os.File,io.Writer+0
	rel 400+4 t=8 fmt.Fprintf+0
	rel 545+4 t=8 runtime.morestack_noctxt+0
"".Gopher.debug STEXT size=554 args=0x18 locals=0x108
	0x0000 00000 (main.go:35)	TEXT	"".Gopher.debug(SB), ABIInternal, $264-24
	0x0000 00000 (main.go:35)	MOVQ	(TLS), CX
	0x0009 00009 (main.go:35)	LEAQ	-136(SP), AX
	0x0011 00017 (main.go:35)	CMPQ	AX, 16(CX)
	0x0015 00021 (main.go:35)	PCDATA	$0, $-2
	0x0015 00021 (main.go:35)	JLS	544
	0x001b 00027 (main.go:35)	PCDATA	$0, $-1
	0x001b 00027 (main.go:35)	SUBQ	$264, SP
	0x0022 00034 (main.go:35)	MOVQ	BP, 256(SP)
	0x002a 00042 (main.go:35)	LEAQ	256(SP), BP
	0x0032 00050 (main.go:35)	FUNCDATA	$0, gclocals·1a65e721a2ccc325b382662e7ffee780(SB)
	0x0032 00050 (main.go:35)	FUNCDATA	$1, gclocals·0c390dd2b680890c3ee1eb04d3729d9e(SB)
	0x0032 00050 (main.go:35)	FUNCDATA	$3, "".Gopher.debug.stkobj(SB)
	0x0032 00050 (main.go:36)	MOVQ	"".p+272(SP), AX
	0x003a 00058 (main.go:36)	MOVQ	"".p+280(SP), CX
	0x0042 00066 (main.go:36)	MOVQ	AX, (SP)
	0x0046 00070 (main.go:36)	MOVQ	CX, 8(SP)
	0x004b 00075 (main.go:36)	PCDATA	$1, $1
	0x004b 00075 (main.go:36)	CALL	runtime.convTstring(SB)
	0x0050 00080 (main.go:36)	MOVQ	16(SP), AX
	0x0055 00085 (main.go:36)	MOVQ	AX, ""..autotmp_11+112(SP)
	0x005a 00090 (main.go:36)	LEAQ	type.string(SB), CX
	0x0061 00097 (main.go:36)	MOVQ	CX, ""..autotmp_10+216(SP)
	0x0069 00105 (main.go:36)	MOVQ	AX, ""..autotmp_10+224(SP)
	0x0071 00113 (main.go:36)	LEAQ	go.string."I am debuging %s language\n"(SB), AX
	0x0078 00120 (main.go:36)	MOVQ	AX, fmt.format+136(SP)
	0x0080 00128 (main.go:36)	MOVQ	$26, fmt.format+144(SP)
	0x008c 00140 (main.go:36)	MOVQ	""..autotmp_10+216(SP), AX
	0x0094 00148 (main.go:36)	MOVQ	""..autotmp_10+224(SP), CX
	0x009c 00156 (main.go:36)	MOVQ	AX, "".~arg1+120(SP)
	0x00a1 00161 (main.go:36)	MOVQ	CX, "".~arg1+128(SP)
	0x00a9 00169 (main.go:36)	XORPS	X0, X0
	0x00ac 00172 (main.go:36)	MOVUPS	X0, ""..autotmp_14+200(SP)
	0x00b4 00180 (main.go:36)	LEAQ	""..autotmp_14+200(SP), AX
	0x00bc 00188 (main.go:36)	MOVQ	AX, ""..autotmp_12+104(SP)
	0x00c1 00193 (main.go:36)	TESTB	AL, (AX)
	0x00c3 00195 (main.go:36)	MOVQ	"".~arg1+120(SP), CX
	0x00c8 00200 (main.go:36)	MOVQ	"".~arg1+128(SP), DX
	0x00d0 00208 (main.go:36)	MOVQ	CX, ""..autotmp_14+200(SP)
	0x00d8 00216 (main.go:36)	MOVQ	DX, ""..autotmp_14+208(SP)
	0x00e0 00224 (main.go:36)	TESTB	AL, (AX)
	0x00e2 00226 (main.go:36)	JMP	228
	0x00e4 00228 (main.go:36)	MOVQ	AX, fmt.a+232(SP)
	0x00ec 00236 (main.go:36)	MOVQ	$1, fmt.a+240(SP)
	0x00f8 00248 (main.go:36)	MOVQ	$1, fmt.a+248(SP)
	0x0104 00260 (main.go:36)	MOVQ	$0, fmt.n+80(SP)
	0x010d 00269 (main.go:36)	XORPS	X0, X0
	0x0110 00272 (main.go:36)	MOVUPS	X0, fmt.err+152(SP)
	0x0118 00280 (<unknown line number>)	NOP
	0x0118 00280 (main.go:32)	MOVQ	$0, fmt..autotmp_4+96(SP)
	0x0121 00289 (main.go:32)	XORPS	X0, X0
	0x0124 00292 (main.go:32)	MOVUPS	X0, fmt..autotmp_5+184(SP)
	0x012c 00300 ($GOROOT/src/fmt/print.go:213)	XORPS	X0, X0
	0x012f 00303 ($GOROOT/src/fmt/print.go:213)	MOVUPS	X0, ""..autotmp_9+168(SP)
	0x0137 00311 ($GOROOT/src/fmt/print.go:213)	MOVQ	os.Stdout(SB), AX
	0x013e 00318 ($GOROOT/src/fmt/print.go:213)	LEAQ	go.itab.*os.File,io.Writer(SB), CX
	0x0145 00325 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, (SP)
	0x0149 00329 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, 8(SP)
	0x014e 00334 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.format+136(SP), AX
	0x0156 00342 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.format+144(SP), CX
	0x015e 00350 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, 16(SP)
	0x0163 00355 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, 24(SP)
	0x0168 00360 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.a+232(SP), AX
	0x0170 00368 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.a+240(SP), CX
	0x0178 00376 ($GOROOT/src/fmt/print.go:213)	MOVQ	fmt.a+248(SP), DX
	0x0180 00384 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, 32(SP)
	0x0185 00389 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, 40(SP)
	0x018a 00394 ($GOROOT/src/fmt/print.go:213)	MOVQ	DX, 48(SP)
	0x018f 00399 ($GOROOT/src/fmt/print.go:213)	CALL	fmt.Fprintf(SB)
	0x0194 00404 ($GOROOT/src/fmt/print.go:213)	MOVQ	56(SP), AX
	0x0199 00409 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, ""..autotmp_8+88(SP)
	0x019e 00414 ($GOROOT/src/fmt/print.go:213)	MOVQ	64(SP), AX
	0x01a3 00419 ($GOROOT/src/fmt/print.go:213)	MOVQ	72(SP), CX
	0x01a8 00424 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, ""..autotmp_9+168(SP)
	0x01b0 00432 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, ""..autotmp_9+176(SP)
	0x01b8 00440 ($GOROOT/src/fmt/print.go:213)	MOVQ	""..autotmp_8+88(SP), AX
	0x01bd 00445 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, fmt..autotmp_4+96(SP)
	0x01c2 00450 ($GOROOT/src/fmt/print.go:213)	MOVQ	""..autotmp_9+168(SP), AX
	0x01ca 00458 ($GOROOT/src/fmt/print.go:213)	MOVQ	""..autotmp_9+176(SP), CX
	0x01d2 00466 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, fmt..autotmp_5+184(SP)
	0x01da 00474 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, fmt..autotmp_5+192(SP)
	0x01e2 00482 (main.go:36)	MOVQ	fmt..autotmp_4+96(SP), AX
	0x01e7 00487 (main.go:36)	MOVQ	AX, fmt.n+80(SP)
	0x01ec 00492 (main.go:36)	MOVQ	fmt..autotmp_5+184(SP), AX
	0x01f4 00500 (main.go:36)	MOVQ	fmt..autotmp_5+192(SP), CX
	0x01fc 00508 (main.go:36)	MOVQ	AX, fmt.err+152(SP)
	0x0204 00516 (main.go:36)	MOVQ	CX, fmt.err+160(SP)
	0x020c 00524 (main.go:36)	JMP	526
	0x020e 00526 (main.go:36)	PCDATA	$1, $-1
	0x020e 00526 (main.go:36)	MOVQ	256(SP), BP
	0x0216 00534 (main.go:36)	ADDQ	$264, SP
	0x021d 00541 (main.go:36)	RET
	0x021e 00542 (main.go:36)	NOP
	0x021e 00542 (main.go:35)	PCDATA	$1, $-1
	0x021e 00542 (main.go:35)	PCDATA	$0, $-2
	0x021e 00542 (main.go:35)	NOP
	0x0220 00544 (main.go:35)	CALL	runtime.morestack_noctxt(SB)
	0x0225 00549 (main.go:35)	PCDATA	$0, $-1
	0x0225 00549 (main.go:35)	JMP	0
	0x0000 65 48 8b 0c 25 00 00 00 00 48 8d 84 24 78 ff ff  eH..%....H..$x..
	0x0010 ff 48 3b 41 10 0f 86 05 02 00 00 48 81 ec 08 01  .H;A.......H....
	0x0020 00 00 48 89 ac 24 00 01 00 00 48 8d ac 24 00 01  ..H..$....H..$..
	0x0030 00 00 48 8b 84 24 10 01 00 00 48 8b 8c 24 18 01  ..H..$....H..$..
	0x0040 00 00 48 89 04 24 48 89 4c 24 08 e8 00 00 00 00  ..H..$H.L$......
	0x0050 48 8b 44 24 10 48 89 44 24 70 48 8d 0d 00 00 00  H.D$.H.D$pH.....
	0x0060 00 48 89 8c 24 d8 00 00 00 48 89 84 24 e0 00 00  .H..$....H..$...
	0x0070 00 48 8d 05 00 00 00 00 48 89 84 24 88 00 00 00  .H......H..$....
	0x0080 48 c7 84 24 90 00 00 00 1a 00 00 00 48 8b 84 24  H..$........H..$
	0x0090 d8 00 00 00 48 8b 8c 24 e0 00 00 00 48 89 44 24  ....H..$....H.D$
	0x00a0 78 48 89 8c 24 80 00 00 00 0f 57 c0 0f 11 84 24  xH..$.....W....$
	0x00b0 c8 00 00 00 48 8d 84 24 c8 00 00 00 48 89 44 24  ....H..$....H.D$
	0x00c0 68 84 00 48 8b 4c 24 78 48 8b 94 24 80 00 00 00  h..H.L$xH..$....
	0x00d0 48 89 8c 24 c8 00 00 00 48 89 94 24 d0 00 00 00  H..$....H..$....
	0x00e0 84 00 eb 00 48 89 84 24 e8 00 00 00 48 c7 84 24  ....H..$....H..$
	0x00f0 f0 00 00 00 01 00 00 00 48 c7 84 24 f8 00 00 00  ........H..$....
	0x0100 01 00 00 00 48 c7 44 24 50 00 00 00 00 0f 57 c0  ....H.D$P.....W.
	0x0110 0f 11 84 24 98 00 00 00 48 c7 44 24 60 00 00 00  ...$....H.D$`...
	0x0120 00 0f 57 c0 0f 11 84 24 b8 00 00 00 0f 57 c0 0f  ..W....$.....W..
	0x0130 11 84 24 a8 00 00 00 48 8b 05 00 00 00 00 48 8d  ..$....H......H.
	0x0140 0d 00 00 00 00 48 89 0c 24 48 89 44 24 08 48 8b  .....H..$H.D$.H.
	0x0150 84 24 88 00 00 00 48 8b 8c 24 90 00 00 00 48 89  .$....H..$....H.
	0x0160 44 24 10 48 89 4c 24 18 48 8b 84 24 e8 00 00 00  D$.H.L$.H..$....
	0x0170 48 8b 8c 24 f0 00 00 00 48 8b 94 24 f8 00 00 00  H..$....H..$....
	0x0180 48 89 44 24 20 48 89 4c 24 28 48 89 54 24 30 e8  H.D$ H.L$(H.T$0.
	0x0190 00 00 00 00 48 8b 44 24 38 48 89 44 24 58 48 8b  ....H.D$8H.D$XH.
	0x01a0 44 24 40 48 8b 4c 24 48 48 89 84 24 a8 00 00 00  D$@H.L$HH..$....
	0x01b0 48 89 8c 24 b0 00 00 00 48 8b 44 24 58 48 89 44  H..$....H.D$XH.D
	0x01c0 24 60 48 8b 84 24 a8 00 00 00 48 8b 8c 24 b0 00  $`H..$....H..$..
	0x01d0 00 00 48 89 84 24 b8 00 00 00 48 89 8c 24 c0 00  ..H..$....H..$..
	0x01e0 00 00 48 8b 44 24 60 48 89 44 24 50 48 8b 84 24  ..H.D$`H.D$PH..$
	0x01f0 b8 00 00 00 48 8b 8c 24 c0 00 00 00 48 89 84 24  ....H..$....H..$
	0x0200 98 00 00 00 48 89 8c 24 a0 00 00 00 eb 00 48 8b  ....H..$......H.
	0x0210 ac 24 00 01 00 00 48 81 c4 08 01 00 00 c3 66 90  .$....H.......f.
	0x0220 e8 00 00 00 00 e9 d6 fd ff ff                    ..........
	rel 5+4 t=17 TLS+0
	rel 76+4 t=8 runtime.convTstring+0
	rel 93+4 t=16 type.string+0
	rel 116+4 t=16 go.string."I am debuging %s language\n"+0
	rel 314+4 t=16 os.Stdout+0
	rel 321+4 t=16 go.itab.*os.File,io.Writer+0
	rel 400+4 t=8 fmt.Fprintf+0
	rel 545+4 t=8 runtime.morestack_noctxt+0
"".coder.code STEXT dupok size=92 args=0x10 locals=0x10
	0x0000 00000 (<autogenerated>:1)	TEXT	"".coder.code(SB), DUPOK|WRAPPER|ABIInternal, $16-16
	0x0000 00000 (<autogenerated>:1)	MOVQ	(TLS), CX
	0x0009 00009 (<autogenerated>:1)	CMPQ	SP, 16(CX)
	0x000d 00013 (<autogenerated>:1)	PCDATA	$0, $-2
	0x000d 00013 (<autogenerated>:1)	JLS	70
	0x000f 00015 (<autogenerated>:1)	PCDATA	$0, $-1
	0x000f 00015 (<autogenerated>:1)	SUBQ	$16, SP
	0x0013 00019 (<autogenerated>:1)	MOVQ	BP, 8(SP)
	0x0018 00024 (<autogenerated>:1)	LEAQ	8(SP), BP
	0x001d 00029 (<autogenerated>:1)	MOVQ	32(CX), BX
	0x0021 00033 (<autogenerated>:1)	TESTQ	BX, BX
	0x0024 00036 (<autogenerated>:1)	JNE	77
	0x0026 00038 (<autogenerated>:1)	NOP
	0x0026 00038 (<autogenerated>:1)	FUNCDATA	$0, gclocals·09cf9819fc716118c209c2d2155a3632(SB)
	0x0026 00038 (<autogenerated>:1)	FUNCDATA	$1, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x0026 00038 (<autogenerated>:1)	MOVQ	""..this+24(SP), AX
	0x002b 00043 (<autogenerated>:1)	TESTB	AL, (AX)
	0x002d 00045 (<autogenerated>:1)	MOVQ	24(AX), AX
	0x0031 00049 (<autogenerated>:1)	MOVQ	""..this+32(SP), CX
	0x0036 00054 (<autogenerated>:1)	MOVQ	CX, (SP)
	0x003a 00058 (<autogenerated>:1)	PCDATA	$1, $1
	0x003a 00058 (<autogenerated>:1)	CALL	AX
	0x003c 00060 (<autogenerated>:1)	MOVQ	8(SP), BP
	0x0041 00065 (<autogenerated>:1)	ADDQ	$16, SP
	0x0045 00069 (<autogenerated>:1)	RET
	0x0046 00070 (<autogenerated>:1)	NOP
	0x0046 00070 (<autogenerated>:1)	PCDATA	$1, $-1
	0x0046 00070 (<autogenerated>:1)	PCDATA	$0, $-2
	0x0046 00070 (<autogenerated>:1)	CALL	runtime.morestack_noctxt(SB)
	0x004b 00075 (<autogenerated>:1)	PCDATA	$0, $-1
	0x004b 00075 (<autogenerated>:1)	JMP	0
	0x004d 00077 (<autogenerated>:1)	LEAQ	24(SP), DI
	0x0052 00082 (<autogenerated>:1)	CMPQ	(BX), DI
	0x0055 00085 (<autogenerated>:1)	JNE	38
	0x0057 00087 (<autogenerated>:1)	MOVQ	SP, (BX)
	0x005a 00090 (<autogenerated>:1)	JMP	38
	0x0000 65 48 8b 0c 25 00 00 00 00 48 3b 61 10 76 37 48  eH..%....H;a.v7H
	0x0010 83 ec 10 48 89 6c 24 08 48 8d 6c 24 08 48 8b 59  ...H.l$.H.l$.H.Y
	0x0020 20 48 85 db 75 27 48 8b 44 24 18 84 00 48 8b 40   H..u'H.D$...H.@
	0x0030 18 48 8b 4c 24 20 48 89 0c 24 ff d0 48 8b 6c 24  .H.L$ H..$..H.l$
	0x0040 08 48 83 c4 10 c3 e8 00 00 00 00 eb b3 48 8d 7c  .H...........H.|
	0x0050 24 18 48 39 3b 75 cf 48 89 23 eb ca              $.H9;u.H.#..
	rel 5+4 t=17 TLS+0
	rel 58+0 t=11 +0
	rel 71+4 t=8 runtime.morestack_noctxt+0
"".coder.debug STEXT dupok size=92 args=0x10 locals=0x10
	0x0000 00000 (<autogenerated>:1)	TEXT	"".coder.debug(SB), DUPOK|WRAPPER|ABIInternal, $16-16
	0x0000 00000 (<autogenerated>:1)	MOVQ	(TLS), CX
	0x0009 00009 (<autogenerated>:1)	CMPQ	SP, 16(CX)
	0x000d 00013 (<autogenerated>:1)	PCDATA	$0, $-2
	0x000d 00013 (<autogenerated>:1)	JLS	70
	0x000f 00015 (<autogenerated>:1)	PCDATA	$0, $-1
	0x000f 00015 (<autogenerated>:1)	SUBQ	$16, SP
	0x0013 00019 (<autogenerated>:1)	MOVQ	BP, 8(SP)
	0x0018 00024 (<autogenerated>:1)	LEAQ	8(SP), BP
	0x001d 00029 (<autogenerated>:1)	MOVQ	32(CX), BX
	0x0021 00033 (<autogenerated>:1)	TESTQ	BX, BX
	0x0024 00036 (<autogenerated>:1)	JNE	77
	0x0026 00038 (<autogenerated>:1)	NOP
	0x0026 00038 (<autogenerated>:1)	FUNCDATA	$0, gclocals·09cf9819fc716118c209c2d2155a3632(SB)
	0x0026 00038 (<autogenerated>:1)	FUNCDATA	$1, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x0026 00038 (<autogenerated>:1)	MOVQ	""..this+24(SP), AX
	0x002b 00043 (<autogenerated>:1)	TESTB	AL, (AX)
	0x002d 00045 (<autogenerated>:1)	MOVQ	32(AX), AX
	0x0031 00049 (<autogenerated>:1)	MOVQ	""..this+32(SP), CX
	0x0036 00054 (<autogenerated>:1)	MOVQ	CX, (SP)
	0x003a 00058 (<autogenerated>:1)	PCDATA	$1, $1
	0x003a 00058 (<autogenerated>:1)	CALL	AX
	0x003c 00060 (<autogenerated>:1)	MOVQ	8(SP), BP
	0x0041 00065 (<autogenerated>:1)	ADDQ	$16, SP
	0x0045 00069 (<autogenerated>:1)	RET
	0x0046 00070 (<autogenerated>:1)	NOP
	0x0046 00070 (<autogenerated>:1)	PCDATA	$1, $-1
	0x0046 00070 (<autogenerated>:1)	PCDATA	$0, $-2
	0x0046 00070 (<autogenerated>:1)	CALL	runtime.morestack_noctxt(SB)
	0x004b 00075 (<autogenerated>:1)	PCDATA	$0, $-1
	0x004b 00075 (<autogenerated>:1)	JMP	0
	0x004d 00077 (<autogenerated>:1)	LEAQ	24(SP), DI
	0x0052 00082 (<autogenerated>:1)	CMPQ	(BX), DI
	0x0055 00085 (<autogenerated>:1)	JNE	38
	0x0057 00087 (<autogenerated>:1)	MOVQ	SP, (BX)
	0x005a 00090 (<autogenerated>:1)	JMP	38
	0x0000 65 48 8b 0c 25 00 00 00 00 48 3b 61 10 76 37 48  eH..%....H;a.v7H
	0x0010 83 ec 10 48 89 6c 24 08 48 8d 6c 24 08 48 8b 59  ...H.l$.H.l$.H.Y
	0x0020 20 48 85 db 75 27 48 8b 44 24 18 84 00 48 8b 40   H..u'H.D$...H.@
	0x0030 20 48 8b 4c 24 20 48 89 0c 24 ff d0 48 8b 6c 24   H.L$ H..$..H.l$
	0x0040 08 48 83 c4 10 c3 e8 00 00 00 00 eb b3 48 8d 7c  .H...........H.|
	0x0050 24 18 48 39 3b 75 cf 48 89 23 eb ca              $.H9;u.H.#..
	rel 5+4 t=17 TLS+0
	rel 58+0 t=11 +0
	rel 71+4 t=8 runtime.morestack_noctxt+0
go.cuinfo.packagename. SDWARFINFO dupok size=0
	0x0000 6d 61 69 6e                                      main
go.info.fmt.Println$abstract SDWARFINFO dupok size=42
	0x0000 04 66 6d 74 2e 50 72 69 6e 74 6c 6e 00 01 01 11  .fmt.Println....
	0x0010 61 00 00 00 00 00 00 11 6e 00 01 00 00 00 00 11  a.......n.......
	0x0020 65 72 72 00 01 00 00 00 00 00                    err.......
	rel 0+0 t=24 type.[]interface {}+0
	rel 0+0 t=24 type.error+0
	rel 0+0 t=24 type.int+0
	rel 19+4 t=29 go.info.[]interface {}+0
	rel 27+4 t=29 go.info.int+0
	rel 37+4 t=29 go.info.error+0
go.info.fmt.Printf$abstract SDWARFINFO dupok size=54
	0x0000 04 66 6d 74 2e 50 72 69 6e 74 66 00 01 01 11 66  .fmt.Printf....f
	0x0010 6f 72 6d 61 74 00 00 00 00 00 00 11 61 00 00 00  ormat.......a...
	0x0020 00 00 00 11 6e 00 01 00 00 00 00 11 65 72 72 00  ....n.......err.
	0x0030 01 00 00 00 00 00                                ......
	rel 0+0 t=24 type.[]interface {}+0
	rel 0+0 t=24 type.error+0
	rel 0+0 t=24 type.int+0
	rel 0+0 t=24 type.string+0
	rel 23+4 t=29 go.info.string+0
	rel 31+4 t=29 go.info.[]interface {}+0
	rel 39+4 t=29 go.info.int+0
	rel 49+4 t=29 go.info.error+0
go.string."Go" SRODATA dupok size=2
	0x0000 47 6f                                            Go
type..eqfunc."".Gopher SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 type..eq."".Gopher+0
runtime.memequal64·f SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 runtime.memequal64+0
runtime.gcbits.01 SRODATA dupok size=1
	0x0000 01                                               .
go.info."".Gopher.code$abstract SDWARFINFO dupok size=25
	0x0000 04 2e 47 6f 70 68 65 72 2e 63 6f 64 65 00 01 01  ..Gopher.code...
	0x0010 11 70 00 00 00 00 00 00 00                       .p.......
	rel 0+0 t=24 type."".Gopher+0
	rel 20+4 t=29 go.info."".Gopher+0
go.string."I am coding %s language\n" SRODATA dupok size=24
	0x0000 49 20 61 6d 20 63 6f 64 69 6e 67 20 25 73 20 6c  I am coding %s l
	0x0010 61 6e 67 75 61 67 65 0a                          anguage.
runtime.nilinterequal·f SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 runtime.nilinterequal+0
type..namedata.*interface {}- SRODATA dupok size=16
	0x0000 00 00 0d 2a 69 6e 74 65 72 66 61 63 65 20 7b 7d  ...*interface {}
type.*interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 4f 0f 96 9d 08 08 08 36 00 00 00 00 00 00 00 00  O......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*interface {}-+0
	rel 48+8 t=1 type.interface {}+0
runtime.gcbits.02 SRODATA dupok size=1
	0x0000 02                                               .
type.interface {} SRODATA dupok size=80
	0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	0x0010 e7 57 a0 18 02 08 08 14 00 00 00 00 00 00 00 00  .W..............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 24+8 t=1 runtime.nilinterequal·f+0
	rel 32+8 t=1 runtime.gcbits.02+0
	rel 40+4 t=5 type..namedata.*interface {}-+0
	rel 44+4 t=6 type.*interface {}+0
	rel 56+8 t=1 type.interface {}+80
type..namedata.*[]interface {}- SRODATA dupok size=18
	0x0000 00 00 0f 2a 5b 5d 69 6e 74 65 72 66 61 63 65 20  ...*[]interface 
	0x0010 7b 7d                                            {}
type.*[]interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 f3 04 9a e7 08 08 08 36 00 00 00 00 00 00 00 00  .......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]interface {}-+0
	rel 48+8 t=1 type.[]interface {}+0
type.[]interface {} SRODATA dupok size=56
	0x0000 18 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 70 93 ea 2f 02 08 08 17 00 00 00 00 00 00 00 00  p../............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]interface {}-+0
	rel 44+4 t=6 type.*[]interface {}+0
	rel 48+8 t=1 type.interface {}+0
type..namedata.*[1]interface {}- SRODATA dupok size=19
	0x0000 00 00 10 2a 5b 31 5d 69 6e 74 65 72 66 61 63 65  ...*[1]interface
	0x0010 20 7b 7d                                          {}
type.*[1]interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 bf 03 a8 35 08 08 08 36 00 00 00 00 00 00 00 00  ...5...6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[1]interface {}-+0
	rel 48+8 t=1 type.[1]interface {}+0
type.[1]interface {} SRODATA dupok size=72
	0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	0x0010 50 91 5b fa 02 08 08 11 00 00 00 00 00 00 00 00  P.[.............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 01 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.nilinterequal·f+0
	rel 32+8 t=1 runtime.gcbits.02+0
	rel 40+4 t=5 type..namedata.*[1]interface {}-+0
	rel 44+4 t=6 type.*[1]interface {}+0
	rel 48+8 t=1 type.interface {}+0
	rel 56+8 t=1 type.[]interface {}+0
go.info."".Gopher.debug$abstract SDWARFINFO dupok size=26
	0x0000 04 2e 47 6f 70 68 65 72 2e 64 65 62 75 67 00 01  ..Gopher.debug..
	0x0010 01 11 70 00 00 00 00 00 00 00                    ..p.......
	rel 0+0 t=24 type."".Gopher+0
	rel 21+4 t=29 go.info."".Gopher+0
go.string."I am debuging %s language\n" SRODATA dupok size=26
	0x0000 49 20 61 6d 20 64 65 62 75 67 69 6e 67 20 25 73  I am debuging %s
	0x0010 20 6c 61 6e 67 75 61 67 65 0a                     language.
type..namedata.*main.Gopher. SRODATA dupok size=15
	0x0000 01 00 0c 2a 6d 61 69 6e 2e 47 6f 70 68 65 72     ...*main.Gopher
type..namedata.*func(*main.Gopher)- SRODATA dupok size=22
	0x0000 00 00 13 2a 66 75 6e 63 28 2a 6d 61 69 6e 2e 47  ...*func(*main.G
	0x0010 6f 70 68 65 72 29                                opher)
type.*func(*"".Gopher) SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 a3 c4 a7 0a 08 08 08 36 00 00 00 00 00 00 00 00  .......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*func(*main.Gopher)-+0
	rel 48+8 t=1 type.func(*"".Gopher)+0
type.func(*"".Gopher) SRODATA dupok size=64
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 e1 b0 70 ba 02 08 08 33 00 00 00 00 00 00 00 00  ..p....3........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*func(*main.Gopher)-+0
	rel 44+4 t=6 type.*func(*"".Gopher)+0
	rel 56+8 t=1 type.*"".Gopher+0
type..namedata.code- SRODATA dupok size=7
	0x0000 00 00 04 63 6f 64 65                             ...code
type..namedata.*func()- SRODATA dupok size=10
	0x0000 00 00 07 2a 66 75 6e 63 28 29                    ...*func()
type.*func() SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 9b 90 75 1b 08 08 08 36 00 00 00 00 00 00 00 00  ..u....6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*func()-+0
	rel 48+8 t=1 type.func()+0
type.func() SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 f6 bc 82 f6 02 08 08 33 00 00 00 00 00 00 00 00  .......3........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00                                      ....
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*func()-+0
	rel 44+4 t=6 type.*func()+0
type..namedata.debug- SRODATA dupok size=8
	0x0000 00 00 05 64 65 62 75 67                          ...debug
type.*"".Gopher SRODATA size=104
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 ed 07 27 8c 09 08 08 36 00 00 00 00 00 00 00 00  ..'....6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00  ................
	0x0040 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0060 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*main.Gopher.+0
	rel 48+8 t=1 type."".Gopher+0
	rel 56+4 t=5 type..importpath."".+0
	rel 72+4 t=5 type..namedata.code-+0
	rel 76+4 t=25 type.func()+0
	rel 80+4 t=25 "".(*Gopher).code+0
	rel 84+4 t=25 "".(*Gopher).code+0
	rel 88+4 t=5 type..namedata.debug-+0
	rel 92+4 t=25 type.func()+0
	rel 96+4 t=25 "".(*Gopher).debug+0
	rel 100+4 t=25 "".(*Gopher).debug+0
type..namedata.*func(main.Gopher)- SRODATA dupok size=21
	0x0000 00 00 12 2a 66 75 6e 63 28 6d 61 69 6e 2e 47 6f  ...*func(main.Go
	0x0010 70 68 65 72 29                                   pher)
type.*func("".Gopher) SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 fe b8 05 90 08 08 08 36 00 00 00 00 00 00 00 00  .......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*func(main.Gopher)-+0
	rel 48+8 t=1 type.func("".Gopher)+0
type.func("".Gopher) SRODATA dupok size=64
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 40 58 c1 7c 02 08 08 33 00 00 00 00 00 00 00 00  @X.|...3........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*func(main.Gopher)-+0
	rel 44+4 t=6 type.*func("".Gopher)+0
	rel 56+8 t=1 type."".Gopher+0
type..namedata.language- SRODATA dupok size=11
	0x0000 00 00 08 6c 61 6e 67 75 61 67 65                 ...language
type..namedata.Level. SRODATA dupok size=8
	0x0000 01 00 05 4c 65 76 65 6c                          ...Level
type."".Gopher SRODATA size=176
	0x0000 18 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 02 2c fd 86 07 08 08 19 00 00 00 00 00 00 00 00  .,..............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 02 00 00 00 00 00 00 00 02 00 00 00 00 00 00 00  ................
	0x0050 00 00 00 00 02 00 00 00 40 00 00 00 00 00 00 00  ........@.......
	0x0060 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0080 00 00 00 00 00 00 00 00 20 00 00 00 00 00 00 00  ........ .......
	0x0090 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x00a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 24+8 t=1 type..eqfunc."".Gopher+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*main.Gopher.+0
	rel 44+4 t=5 type.*"".Gopher+0
	rel 48+8 t=1 type..importpath."".+0
	rel 56+8 t=1 type."".Gopher+96
	rel 80+4 t=5 type..importpath."".+0
	rel 96+8 t=1 type..namedata.language-+0
	rel 104+8 t=1 type.string+0
	rel 120+8 t=1 type..namedata.Level.+0
	rel 128+8 t=1 type.int+0
	rel 144+4 t=5 type..namedata.code-+0
	rel 148+4 t=25 type.func()+0
	rel 152+4 t=25 "".(*Gopher).code+0
	rel 156+4 t=25 "".Gopher.code+0
	rel 160+4 t=5 type..namedata.debug-+0
	rel 164+4 t=25 type.func()+0
	rel 168+4 t=25 "".(*Gopher).debug+0
	rel 172+4 t=25 "".Gopher.debug+0
""..inittask SNOPTRDATA size=32
	0x0000 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00  ................
	0x0010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 24+8 t=1 fmt..inittask+0
runtime.interequal·f SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 runtime.interequal+0
type..namedata.*main.coder- SRODATA dupok size=14
	0x0000 00 00 0b 2a 6d 61 69 6e 2e 63 6f 64 65 72        ...*main.coder
type.*"".coder SRODATA size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 35 a8 c6 33 08 08 08 36 00 00 00 00 00 00 00 00  5..3...6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*main.coder-+0
	rel 48+8 t=1 type."".coder+0
type."".coder SRODATA size=112
	0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	0x0010 d0 2f 69 91 07 08 08 14 00 00 00 00 00 00 00 00  ./i.............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 02 00 00 00 00 00 00 00 02 00 00 00 00 00 00 00  ................
	0x0050 00 00 00 00 00 00 00 00 20 00 00 00 00 00 00 00  ........ .......
	0x0060 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 24+8 t=1 runtime.interequal·f+0
	rel 32+8 t=1 runtime.gcbits.02+0
	rel 40+4 t=5 type..namedata.*main.coder-+0
	rel 44+4 t=5 type.*"".coder+0
	rel 48+8 t=1 type..importpath."".+0
	rel 56+8 t=1 type."".coder+96
	rel 80+4 t=5 type..importpath."".+0
	rel 96+4 t=5 type..namedata.code-+0
	rel 100+4 t=5 type.func()+0
	rel 104+4 t=5 type..namedata.debug-+0
	rel 108+4 t=5 type.func()+0
go.itab.*os.File,io.Writer SRODATA dupok size=32
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 44 b5 f3 33 00 00 00 00 00 00 00 00 00 00 00 00  D..3............
	rel 0+8 t=1 type.io.Writer+0
	rel 8+8 t=1 type.*os.File+0
	rel 24+8 t=1 os.(*File).Write+0
go.itablink.*os.File,io.Writer SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 go.itab.*os.File,io.Writer+0
go.itab."".Gopher,"".coder SRODATA dupok size=40
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 02 2c fd 86 00 00 00 00 00 00 00 00 00 00 00 00  .,..............
	0x0020 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 type."".coder+0
	rel 8+8 t=1 type."".Gopher+0
	rel 24+8 t=1 "".(*Gopher).code+0
	rel 32+8 t=1 "".(*Gopher).debug+0
go.itablink."".Gopher,"".coder SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 go.itab."".Gopher,"".coder+0
type..importpath.fmt. SRODATA dupok size=6
	0x0000 00 00 03 66 6d 74                                ...fmt
gclocals·e6397a44f8e1b6e77d0f200b4fba5269 SRODATA dupok size=10
	0x0000 02 00 00 00 03 00 00 00 01 00                    ..........
gclocals·69c1753bd5f81501d95132d08af04464 SRODATA dupok size=8
	0x0000 02 00 00 00 00 00 00 00                          ........
gclocals·33cdeccccebe80329f1fdbee7f5874cb SRODATA dupok size=8
	0x0000 01 00 00 00 00 00 00 00                          ........
gclocals·12e398377374b01c940a47142b280e95 SRODATA dupok size=14
	0x0000 01 00 00 00 2a 00 00 00 00 00 00 00 00 00        ....*.........
"".main.stkobj SRODATA size=56
	0x0000 03 00 00 00 00 00 00 00 50 ff ff ff ff ff ff ff  ........P.......
	0x0010 00 00 00 00 00 00 00 00 80 ff ff ff ff ff ff ff  ................
	0x0020 00 00 00 00 00 00 00 00 e8 ff ff ff ff ff ff ff  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 16+8 t=1 type.[1]interface {}+0
	rel 32+8 t=1 type.[1]interface {}+0
	rel 48+8 t=1 type."".Gopher+0
gclocals·dc9b0298814590ca3ffc3a889546fc8b SRODATA dupok size=10
	0x0000 02 00 00 00 02 00 00 00 03 00                    ..........
gclocals·2589ca35330fc0fce83503f4569854a0 SRODATA dupok size=10
	0x0000 02 00 00 00 02 00 00 00 00 00                    ..........
gclocals·1a65e721a2ccc325b382662e7ffee780 SRODATA dupok size=10
	0x0000 02 00 00 00 01 00 00 00 01 00                    ..........
gclocals·000713d0e9e44438ca2d32aa6561c14c SRODATA dupok size=14
	0x0000 02 00 00 00 16 00 00 00 00 00 00 00 00 00        ..............
"".(*Gopher).code.stkobj SRODATA dupok size=24
	0x0000 01 00 00 00 00 00 00 00 a0 ff ff ff ff ff ff ff  ................
	0x0010 00 00 00 00 00 00 00 00                          ........
	rel 16+8 t=1 type.[1]interface {}+0
"".(*Gopher).debug.stkobj SRODATA dupok size=24
	0x0000 01 00 00 00 00 00 00 00 a0 ff ff ff ff ff ff ff  ................
	0x0010 00 00 00 00 00 00 00 00                          ........
	rel 16+8 t=1 type.[1]interface {}+0
gclocals·0c390dd2b680890c3ee1eb04d3729d9e SRODATA dupok size=14
	0x0000 02 00 00 00 13 00 00 00 00 00 00 00 00 00        ..............
"".Gopher.code.stkobj SRODATA size=24
	0x0000 01 00 00 00 00 00 00 00 c8 ff ff ff ff ff ff ff  ................
	0x0010 00 00 00 00 00 00 00 00                          ........
	rel 16+8 t=1 type.[1]interface {}+0
"".Gopher.debug.stkobj SRODATA size=24
	0x0000 01 00 00 00 00 00 00 00 c8 ff ff ff ff ff ff ff  ................
	0x0010 00 00 00 00 00 00 00 00                          ........
	rel 16+8 t=1 type.[1]interface {}+0
gclocals·09cf9819fc716118c209c2d2155a3632 SRODATA dupok size=10
	0x0000 02 00 00 00 02 00 00 00 02 00                    ..........
