global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'


scrape_configs:
  - job_name: "go-test"
    scrape_interval: 60s
    scrape_timeout: 60s
    metrics_path: "/metrics"

    static_configs:
      - targets: ["localhost:8888"]
